# Generated by Django 3.2 on 2023-08-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration of the Quiz in minute')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '1.1 Quiz',
                'verbose_name_plural': '1.1 Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[('Single Selection', 'Single Selection'), ('Multiple Selection', 'Multiple Selection'), ('Text', 'Text')], default='Single Selection', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz_app.quiz')),
            ],
            options={
                'verbose_name': '1.2 QuizQuestion',
                'verbose_name_plural': '1.2 QuizQuestions',
            },
        ),
        migrations.CreateModel(
            name='QuizStudentMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mapper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1.4 QuizStudentMapper',
                'verbose_name_plural': '1.4 QuizStudentMappers',
            },
        ),
        migrations.CreateModel(
            name='QuizStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.CharField(max_length=250)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizquestion')),
                ('stu_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_student_mapper_answers', to='quiz_app.quizstudentmapper')),
            ],
            options={
                'verbose_name': '1.4 QuizStudentAnswer',
                'verbose_name_plural': '1.4 QuizStudentAnswers',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='quiz_app.quizquestion')),
            ],
            options={
                'verbose_name': '1.3 QuizQuestionOption',
                'verbose_name_plural': '1.3 QuizQuestionOptions',
            },
        ),
    ]
