# Generated by Django 3.2 on 2023-08-09 10:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
