# Generated by Django 3.2 on 2023-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_alter_quizquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_banner',
            field=models.FileField(blank=True, null=True, upload_to='quiz'),
        ),
    ]
