# Generated by Django 3.2 on 2023-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_quiz_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_answer_point',
            field=models.FloatField(default=0, help_text='point for each correct answer'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='deduction_answer_point',
            field=models.FloatField(default=0, help_text='deduction point for each incorrect answer'),
        ),
        migrations.AddField(
            model_name='quizstudentanswer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizstudentmapper',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
