# Generated by Django 3.2 on 2023-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20230811_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizstudentmapper',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
