# Generated by Django 3.2 on 2021-09-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, choices=[('Student', 'Student'), ('School', 'School')], default='', max_length=250)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, upload_to='images')),
                ('module_lang', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
