# Generated by Django 3.2 on 2021-09-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webinars',
            options={'ordering': ('publish_date',), 'verbose_name': 'Webinars', 'verbose_name_plural': 'Webinars'},
        ),
    ]
