# Generated by Django 3.2 on 2022-10-14 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0005_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamnodQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('phone_num', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diamond_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DiamnodQuery',
                'verbose_name_plural': 'DiamnodQueries',
            },
        ),
    ]
