# Generated by Django 3.2 on 2022-11-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_faqmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='locale',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
    ]
