# Generated by Django 3.2 on 2022-12-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_faqmodel_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmodel',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
