# Generated by Django 3.2 on 2023-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_faqmodel_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('parent_name', models.CharField(max_length=250)),
                ('parent_email', models.EmailField(max_length=250)),
                ('child_name', models.CharField(max_length=250)),
                ('child_email', models.EmailField(max_length=250)),
                ('child_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'ParentInfo',
                'verbose_name_plural': 'ParentInfos',
            },
        ),
    ]
