# Generated by Django 3.2 on 2023-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_parentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='child_email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='child_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='child_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='parent_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
