# Generated by Django 3.2 on 2023-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20230201_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinfo',
            name='school_path',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
