# Generated by Django 3.2 on 2023-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_parentinfo_school_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiesSelectedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('clarity_id', models.CharField(blank=True, max_length=250)),
                ('custom_session_id', models.CharField(blank=True, max_length=250)),
                ('cookies_necessari', models.BooleanField(default=False)),
                ('cookies_esperienza', models.BooleanField(default=False)),
                ('cookies_misurazione', models.BooleanField(default=False)),
                ('cookies_selected_section', models.CharField(blank=True, choices=[('Banner', 'Banner'), ('Popup', 'Popup')], max_length=50)),
            ],
            options={
                'verbose_name': 'CookiesSelectedData',
                'verbose_name_plural': 'CookiesSelectedData',
            },
        ),
    ]
