# Generated by Django 3.2 on 2021-07-21 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0023_alter_blog_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_intent_id', models.CharField(max_length=200)),
                ('payment_method', models.CharField(default='Credit Card', max_length=200)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_type', models.CharField(default='', max_length=200)),
                ('refund', models.CharField(default='', max_length=200)),
                ('dispute_date', models.CharField(default='', max_length=200)),
                ('refund_date', models.CharField(default='', max_length=200)),
                ('amount', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cohorts', to='courses.cohort')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cohorts', to='payment.payment')),
            ],
            options={
                'verbose_name': 'PaymentCohort',
                'verbose_name_plural': 'PaymentCohorts',
            },
        ),
    ]
