# Generated by Django 3.2 on 2021-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_coupon_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcohort',
            name='custom_user_session_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
