# Generated by Django 3.2 on 2021-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_coupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
