# Generated by Django 3.2 on 2021-08-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='program_type',
            field=models.CharField(choices=[('FutureLab', 'FutureLab'), ('General', 'General')], default='Not for any program', max_length=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('FutureLab', 'FutureLab'), ('General', 'General')], default='General', max_length=50),
        ),
    ]
