# Generated by Django 3.2 on 2021-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210812_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='actual_amount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='program_type',
            field=models.CharField(choices=[('Not for any program', 'Not for any program'), ('Extensive', 'Extensive'), ('Core', 'Core')], default='Not for any program', max_length=30),
        ),
    ]
