# Generated by Django 3.2 on 2021-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_coupon_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
