# Generated by Django 3.2 on 2021-09-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20210902_0828'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0011_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='custom_user_session_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Plan', to='courses.ourplans'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PaymentCohort',
        ),
    ]
