# Generated by Django 3.2 on 2021-09-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20210903_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
