# Generated by Django 3.2 on 2021-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_taxcollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_display_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
