# Generated by Django 3.2 on 2021-11-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_tax_tax_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='number_of_plans',
            new_name='number_of_offered_plans',
        ),
    ]
