# Generated by Django 3.2 on 2022-01-24 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0021_rename_number_of_plans_coupon_number_of_offered_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_person_type',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Platform', 'Platform')], default='Platform', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_subscription_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Weekly', 'Weekly')], default='One Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
