# Generated by Django 3.2 on 2022-01-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20220124_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email_id',
            field=models.CharField(blank=True, default='', max_length=75, null=True),
        ),
    ]
