# Generated by Django 3.2 on 2022-01-28 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_auto_20220124_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='email_id',
            new_name='payment_email_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_intent_id',
            new_name='stripe_id',
        ),
    ]
