# Generated by Django 3.2 on 2022-01-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20220128_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_subscription_duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
