# Generated by Django 3.2 on 2022-01-28 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0025_payment_payment_subscription_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('intent_id_of_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(default='0', max_length=50)),
                ('subscription_event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentsubscriptiondetail', to='payment.payment')),
            ],
            options={
                'verbose_name': 'PaymentSubscriptionDetail',
                'verbose_name_plural': 'PaymentSubscriptionDetails',
            },
        ),
    ]
