# Generated by Django 3.2 on 2022-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_paymentsubscriptiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='actual_amount',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='custom_user_session_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dispute_date',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dispute_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_disputed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='Credit Card', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_person_type',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Platform', 'Platform')], default='Platform', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_subscription_type',
            field=models.CharField(blank=True, choices=[('One Time', 'One Time'), ('Weekly', 'Weekly')], default='One Time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_date',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
