# Generated by Django 3.2 on 2022-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20220209_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='skip_course_dependency',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
