# Generated by Django 3.2 on 2022-02-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_coupon_is_course1_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_display_discount_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
