# Generated by Django 3.2 on 2022-07-13 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0062_counselor_company'),
        ('payment', '0032_rename_display_discounted_price_coupon_display_discounted_price_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_information', to='payment.coupon')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school_information', to='userauth.school')),
            ],
            options={
                'verbose_name': 'SchoolInformation',
                'verbose_name_plural': 'SchoolInformations',
            },
        ),
    ]
