# Generated by Django 3.2 on 2022-07-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0062_counselor_company'),
        ('payment', '0033_schoolinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolInformation',
            new_name='Coupondetail',
        ),
        migrations.AlterModelOptions(
            name='coupondetail',
            options={'verbose_name': 'Coupondetail', 'verbose_name_plural': 'Coupondetails'},
        ),
    ]
