# Generated by Django 3.2 on 2022-09-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0078_alter_scholarshiptestquestion_question_type'),
        ('payment', '0034_auto_20220714_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_fully_paid_by_school_or_company',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='coupondetail',
            name='cohort_program1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_cohort_p1_info', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='coupondetail',
            name='cohort_program2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_cohort_p2_info', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='coupondetail',
            name='cohort_program3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_cohort_p3_info', to='courses.cohort'),
        ),
    ]
