# Generated by Django 3.2 on 2022-09-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_auto_20220921_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupondetail',
            options={'verbose_name': 'CouponDetail', 'verbose_name_plural': 'CouponDetails'},
        ),
        migrations.AlterField(
            model_name='coupondetail',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupon_detail', to='payment.coupon'),
        ),
    ]
