# Generated by Django 3.2 on 2022-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_auto_20220921_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_for_middle_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
