# Generated by Django 3.2 on 2023-02-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0078_alter_studentschooldetail_school_type'),
        ('payment', '0037_coupon_is_for_middle_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondetail',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_information', to='userauth.company'),
        ),
    ]
