# Generated by Django 3.2 on 2023-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0037_coupon_is_for_middle_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_for_fast_track_program',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
