# Generated by Django 3.2 on 2023-02-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0038_coupon_is_for_fast_track_program'),
        ('payment', '0038_coupondetail_company'),
    ]

    operations = [
    ]
