# Generated by Django 3.2 on 2023-07-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0112_merge_20230711_0652'),
        ('payment', '0039_merge_20230214_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='courses.ourplans'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='plan_type',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite'), ('Diamond', 'Diamond'), ('Trial2022', 'Trial2022'), ('FastTrack', 'FastTrack'), ('MiddleSchool', 'MiddleSchool'), ('Master', 'Master')], default='Premium', max_length=30),
        ),
    ]
