# Generated by Django 3.2 on 2023-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_auto_20230719_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_for_zanichelli',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
