# Generated by Django 3.2 on 2023-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0041_coupon_is_for_zanichelli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='plan_type',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite'), ('Diamond', 'Diamond'), ('Trial2022', 'Trial2022'), ('FastTrack', 'FastTrack'), ('MiddleSchool', 'MiddleSchool'), ('Master', 'Master'), ('JobCourse', 'JobCourse')], default='Premium', max_length=30),
        ),
    ]
