# Generated by Django 3.2 on 2023-12-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0102_student_stu_sponsor_compnay'),
        ('payment', '0042_alter_coupon_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondetail',
            name='sponsor_compnay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sponsor_company_information', to='userauth.company'),
        ),
    ]
