# Generated by Django 3.2 on 2023-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0005_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('concern', models.TextField()),
                ('subscribe_newsletter', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
