# Generated by Django 3.2 on 2023-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0009_rename_organization_name_contactus_organization_name_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingwebsiteprivacypolicy',
            name='download_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
