# Generated by Django 3.2 on 2023-08-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0010_landingwebsiteprivacypolicy_download_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingwebsiteprivacypolicy',
            old_name='download_file',
            new_name='download_pdf_file_link',
        ),
        migrations.AddField(
            model_name='landingwebsitecookiespolicy',
            name='download_pdf_file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingwebsitetermsofuse',
            name='download_pdf_file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
