# Generated by Django 3.2 on 2023-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0013_websiteprivacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
