# Generated by Django 3.2 on 2023-10-19 05:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_website', '0014_auto_20231009_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.TextField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('download_pdf_file_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TermsAndCondition',
                'verbose_name_plural': 'TermsAndConditions',
            },
        ),
    ]
