# Generated by Django 3.2 on 2021-07-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
