# Generated by Django 3.2 on 2021-07-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDataTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('datatype', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ActionDataType',
                'verbose_name_plural': 'ActionDataTypes',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('module_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_steps', models.IntegerField()),
                ('bg_image', models.FileField(upload_to='images')),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('step_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_action_items', models.IntegerField()),
                ('bg_image', models.FileField(upload_to='images')),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='courses.modules')),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.AddField(
            model_name='modules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='courses.courses'),
        ),
        migrations.CreateModel(
            name='ActionItems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_type', to='courses.actiondatatypes')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item', to='courses.steps')),
            ],
            options={
                'verbose_name': 'ActionItem',
                'verbose_name_plural': 'ActionItems',
            },
        ),
        migrations.CreateModel(
            name='ActionItemLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('file', models.URLField()),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemLink',
                'verbose_name_plural': 'ActionItemLinks',
            },
        ),
        migrations.CreateModel(
            name='ActionItemFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files')),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemFile',
                'verbose_name_plural': 'ActionItemFiles',
            },
        ),
        migrations.CreateModel(
            name='ActionItemDairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('question', models.CharField(max_length=200)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemDairy',
                'verbose_name_plural': 'ActionItemDairies',
            },
        ),
    ]
