# Generated by Django 3.2 on 2021-07-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210703_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionitemlinks',
            old_name='file',
            new_name='link',
        ),
    ]
