# Generated by Django 3.2 on 2021-07-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_file_actionitemlinks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_type', to='courses.actiondatatypes'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='bg_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='courses',
            name='total_modules',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='bg_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='modules',
            name='total_steps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='bg_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='steps',
            name='total_action_items',
            field=models.IntegerField(blank=True),
        ),
    ]
