# Generated by Django 3.2 on 2021-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210705_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='total_modules',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='total_steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='total_action_items',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
