# Generated by Django 3.2 on 2021-07-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210705_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitemdairy',
            options={'verbose_name': 'ActionItemDairy', 'verbose_name_plural': 'ActionItemDairy'},
        ),
    ]
