# Generated by Django 3.2 on 2021-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_actionitemdairy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemdairy',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actionitemfiles',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actionitemlinks',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='modules',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='steps',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
