# Generated by Django 3.2 on 2021-07-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210705_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='cohort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('cohort_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(blank=True, default='', max_length=200)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, default='', max_length=10)),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_course', to='courses.courses')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_module', to='courses.modules')),
            ],
            options={
                'verbose_name': 'cohort',
                'verbose_name_plural': 'cohort',
            },
        ),
        migrations.CreateModel(
            name='step_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('duration', models.CharField(blank=True, default='', max_length=10)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_status', to='courses.cohort')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_name', to='courses.steps')),
            ],
            options={
                'verbose_name': 'step_status',
                'verbose_name_plural': 'step_status',
            },
        ),
    ]
