# Generated by Django 3.2 on 2021-07-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_cohort_step_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemdairy',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='step_status',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_status1', to='courses.cohort'),
        ),
    ]
