# Generated by Django 3.2 on 2021-07-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210706_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='duration',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='total_modules',
        ),
        migrations.RemoveField(
            model_name='modules',
            name='total_steps',
        ),
        migrations.RemoveField(
            model_name='step_status',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='total_action_items',
        ),
    ]
