# Generated by Django 3.2 on 2021-07-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20210707_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLinkTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('linktype', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ActionLinkType',
                'verbose_name_plural': 'ActionLinkTypes',
            },
        ),
        migrations.AlterField(
            model_name='actionitemlinks',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='courses.actionitems'),
        ),
        migrations.AlterField(
            model_name='actionitems',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='courses.steps'),
        ),
    ]
