# Generated by Django 3.2 on 2021-07-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_actionitemlinks_linktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionFileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('filetype', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ActionFileType',
                'verbose_name_plural': 'ActionFileTypes',
            },
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='filetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_types', to='courses.actionfiletypes'),
        ),
    ]
