# Generated by Django 3.2 on 2021-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_actionitemfiles_action_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='introduction_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
