# Generated by Django 3.2 on 2021-07-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_modules_introduction_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('question', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'ActionItemDiary',
                'verbose_name_plural': 'ActionItemDiary',
            },
        ),
        migrations.RemoveField(
            model_name='actionitemdairy',
            name='action_item',
        ),
        migrations.AddField(
            model_name='cohort',
            name='is_active',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
