# Generated by Django 3.2 on 2021-07-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210720_0415'),
        ('courses', '0018_auto_20210720_0415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionItemDairy',
        ),
        migrations.AddField(
            model_name='actionitemdiary',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='courses.actionitems'),
        ),
    ]
