# Generated by Django 3.2 on 2021-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='icon',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
