# Generated by Django 3.2 on 2021-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_blog_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='module_priority',
            field=models.IntegerField(default='0'),
        ),
    ]
