# Generated by Django 3.2 on 2021-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_modules_module_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='webinars',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
