# Generated by Django 3.2 on 2021-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_type',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
