# Generated by Django 3.2 on 2021-07-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20210726_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='module_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
    ]
