# Generated by Django 3.2 on 2021-07-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_modules_module_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('resource_title', models.CharField(max_length=70)),
                ('resource_description', models.TextField(blank=True, default='')),
                ('resource_link', models.URLField()),
            ],
            options={
                'verbose_name': 'MyResource',
                'verbose_name_plural': 'MyResources',
            },
        ),
        migrations.CreateModel(
            name='MyVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('video_title', models.CharField(max_length=70)),
                ('video_link', models.URLField()),
                ('video_description', models.TextField(blank=True, default='')),
                ('front_pic', models.FileField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'MyVideo',
                'verbose_name_plural': 'MyVideos',
            },
        ),
        migrations.CreateModel(
            name='MyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('group_title', models.CharField(max_length=70)),
                ('group_link', models.URLField()),
                ('group_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('facebook', 'Facebook')], default='whatsapp', max_length=20)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mygroups', to='courses.cohort')),
            ],
            options={
                'verbose_name': 'MyGroup',
                'verbose_name_plural': 'MyGroups',
            },
        ),
    ]
