# Generated by Django 3.2 on 2021-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_mygroups_myresources_myvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='myresources',
            name='resource_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
        migrations.AddField(
            model_name='myvideos',
            name='video_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
    ]
