# Generated by Django 3.2 on 2021-07-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20210728_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='module_lang',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='myresources',
            old_name='resource_lang',
            new_name='lang',
        ),
        migrations.RenameField(
            model_name='myvideos',
            old_name='video_lang',
            new_name='lang',
        ),
    ]
