# Generated by Django 3.2 on 2021-07-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210728_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='lang',
            new_name='module_lang',
        ),
        migrations.RenameField(
            model_name='myresources',
            old_name='lang',
            new_name='module_lang',
        ),
        migrations.RenameField(
            model_name='myvideos',
            old_name='lang',
            new_name='module_lang',
        ),
    ]
