# Generated by Django 3.2 on 2021-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20210728_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='module_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
        migrations.AddField(
            model_name='webinars',
            name='module_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
    ]
