# Generated by Django 3.2 on 2021-07-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20210729_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonNotification',
        ),
    ]
