# Generated by Django 3.2 on 2021-08-11 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_delete_personnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBlogVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('icon', models.FileField(blank=True, upload_to='images')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('module_lang', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('blogs', 'Blogs'), ('videos', 'Videos')], default='blogs', max_length=20)),
            ],
            options={
                'verbose_name': 'MyBlogVideo',
                'verbose_name_plural': 'MyBlogVideos',
                'ordering': ('-publish_date',),
            },
        ),
    ]
