# Generated by Django 3.2 on 2021-08-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_myblogvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('plan_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'OurPlansName',
                'verbose_name_plural': 'OurPlansNames',
            },
        ),
        migrations.AlterModelOptions(
            name='webinars',
            options={'ordering': ('-publish_date',), 'verbose_name': 'Webinars', 'verbose_name_plural': 'Webinars'},
        ),
        migrations.CreateModel(
            name='OurPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('introduction_video', models.URLField(blank=True)),
                ('cost', models.CharField(blank=True, default='', max_length=10)),
                ('upgrade_cost', models.CharField(blank=True, default='', max_length=10)),
                ('plan_lang', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20)),
                ('plan_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='courses.plansname')),
            ],
            options={
                'verbose_name': 'OurPlan',
                'verbose_name_plural': 'OurPlans',
            },
        ),
    ]
