# Generated by Django 3.2 on 2021-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20210901_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourplans',
            name='plan_name',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Elite', 'Elite')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PlansName',
        ),
    ]
