# Generated by Django 3.2 on 2021-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20210908_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step_status',
            options={'ordering': ['step__step_sno'], 'verbose_name': 'step_status', 'verbose_name_plural': 'step_status'},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'ordering': ('step_sno',), 'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AddField(
            model_name='steps',
            name='step_sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
