# Generated by Django 3.2 on 2021-09-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20210909_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webinars',
            options={'ordering': ('publish_date',), 'verbose_name': 'Webinars', 'verbose_name_plural': 'Webinars'},
        ),
    ]
