# Generated by Django 3.2 on 2021-09-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_webinars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'verbose_name': 'Cohort', 'verbose_name_plural': 'Cohort'},
        ),
    ]
