# Generated by Django 3.2 on 2021-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_cohort_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourplans',
            name='plan_name',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite')], max_length=20),
        ),
    ]
