# Generated by Django 3.2 on 2021-10-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_meetup_meetupcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='step_status',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='courses.step_status'),
        ),
    ]
