# Generated by Django 3.2 on 2021-10-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_meetup_step_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='step_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to='courses.step_status'),
        ),
    ]
