# Generated by Django 3.2 on 2021-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20211014_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ('meet_date_time',), 'verbose_name': 'Meetup', 'verbose_name_plural': 'Meetups'},
        ),
        migrations.AddField(
            model_name='meetupcommunity',
            name='meetup_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
    ]
