# Generated by Django 3.2 on 2021-11-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20211031_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
