# Generated by Django 3.2 on 2021-11-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_modules_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
