# Generated by Django 3.2 on 2021-11-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_modules_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='cohort_type',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Trial', 'Trial'), ('Test', 'Test')], default='Paid', max_length=20, null=True),
        ),
    ]
