# Generated by Django 3.2 on 2021-12-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_cohort_cohort_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemExitTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('question', models.CharField(max_length=1000)),
                ('type', models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Other', 'Other')], default='Other', max_length=200, null=True)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_tickets', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemExitTicket',
                'verbose_name_plural': 'ActionItemExitTickets',
                'ordering': ('sno',),
            },
        ),
        migrations.CreateModel(
            name='ActionItemExitTicketOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('option', models.CharField(max_length=200)),
                ('action_item_exit_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_ticket_options', to='courses.actionitemexitticket')),
            ],
            options={
                'verbose_name': 'ActionItemExitTicketOption',
                'verbose_name_plural': 'ActionItemExitTicketOptions',
                'ordering': ('sno',),
            },
        ),
    ]
