# Generated by Django 3.2 on 2021-12-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_actionitemexitticket_actionitemexitticketoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitemdiary',
            options={'ordering': ('sno',), 'verbose_name': 'ActionItemDiary', 'verbose_name_plural': 'ActionItemDiary'},
        ),
        migrations.AlterModelOptions(
            name='actionitemfiles',
            options={'ordering': ('sno',), 'verbose_name': 'ActionItemFile', 'verbose_name_plural': 'ActionItemFiles'},
        ),
        migrations.AlterModelOptions(
            name='actionitemlinks',
            options={'ordering': ('sno',), 'verbose_name': 'ActionItemLink', 'verbose_name_plural': 'ActionItemLinks'},
        ),
        migrations.AddField(
            model_name='actionitemdiary',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='actionitemlinks',
            name='sno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='actionitemexitticket',
            name='type',
            field=models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Rating', 'Rating'), ('Other', 'Other')], default='Other', max_length=200, null=True),
        ),
    ]
