# Generated by Django 3.2 on 2022-01-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='modified_by',
        ),
    ]
