# Generated by Django 3.2 on 2022-01-05 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_auto_20220105_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='EmailForwadingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('excel_file', models.FileField(upload_to='excel_data')),
                ('emailtemplate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceldata', to='courses.emailtemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
