# Generated by Django 3.2 on 2022-03-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_merge_20220207_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
            ],
            options={
                'verbose_name': 'PersonalityTest',
                'verbose_name_plural': 'PersonalityTests',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('Realistic', 'Realistic'), ('Investigative ', 'Investigative '), ('Artistic ', 'Artistic '), ('Social ', 'Social '), ('Enterprising ', 'Enterprising '), ('Conventional ', 'Conventional ')], max_length=50, null=True)),
                ('personality_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalitytestquestions', to='courses.personalitytest')),
            ],
            options={
                'verbose_name': 'PersonalityTestQuestion',
                'verbose_name_plural': 'PersonalityTestQuestions',
            },
        ),
        migrations.CreateModel(
            name='PTQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('options', models.CharField(blank=True, choices=[('Agree', 'Agree'), ('Disagree', 'Disagree')], max_length=50, null=True)),
                ('personality_test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptquestionoptions', to='courses.personalitytestquestion')),
            ],
            options={
                'verbose_name': 'PTQuestionOption',
                'verbose_name_plural': 'PTQuestionOptions',
            },
        ),
    ]
