# Generated by Django 3.2 on 2022-03-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_personalitytest_personalitytestquestion_ptquestionoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptquestionoption',
            old_name='options',
            new_name='option',
        ),
    ]
