# Generated by Django 3.2 on 2022-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_rename_options_ptquestionoption_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytestquestion',
            name='category',
            field=models.CharField(blank=True, choices=[('Realistic', 'Realistic'), ('Investigative', 'Investigative'), ('Artistic', 'Artistic'), ('Social', 'Social'), ('Enterprising', 'Enterprising'), ('Conventional', 'Conventional')], max_length=50, null=True),
        ),
    ]
