# Generated by Django 3.2 on 2022-07-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_alter_personalitytestquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
            ],
            options={
                'verbose_name': 'ScholarshipTestQuestion',
                'verbose_name_plural': 'ScholarshipTestQuestions',
            },
        ),
    ]
