# Generated by Django 3.2 on 2022-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_scholarshiptestquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourplans',
            name='pcto_hour_limit',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='allocated_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='maximum_seats',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='pcto_hours',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_accessibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='webinars', to='courses.ourplans'),
        ),
    ]
