# Generated by Django 3.2 on 2022-07-29 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_auto_20220726_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='seat_book_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
