# Generated by Django 3.2 on 2022-08-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_delete_scholarshiptestquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
            ],
            options={
                'verbose_name': 'ScholarshipTest',
                'verbose_name_plural': 'ScholarshipTests',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('question', models.CharField(blank=True, max_length=250, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('scholarship_test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_test_questions', to='courses.scholarshiptest')),
            ],
            options={
                'verbose_name': 'ScholarshipTestQuestion',
                'verbose_name_plural': 'ScholarshipTestQuestions',
            },
        ),
    ]
