# Generated by Django 3.2 on 2022-08-04 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_scholarshiptest_scholarshiptestquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinars',
            old_name='seat_book_date',
            new_name='reservation_start_date',
        ),
        migrations.AddField(
            model_name='webinars',
            name='datetime_to_mark_attendance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
