# Generated by Django 3.2 on 2022-08-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_auto_20220804_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinars',
            name='webinar_accessibility',
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_accessibility',
            field=models.ManyToManyField(to='courses.OurPlans'),
        ),
    ]
