# Generated by Django 3.2 on 2022-09-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0071_auto_20220831_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiptestquestion',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('Option', 'Option')], default='Text', max_length=20),
        ),
    ]
