# Generated by Django 3.2 on 2022-09-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_pushnotificationrecords_pushnotificationtopics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationrecords',
            options={'verbose_name': 'PushNotificationRecord', 'verbose_name_plural': 'PushNotificationRecords'},
        ),
        migrations.AlterModelOptions(
            name='pushnotificationtopics',
            options={'verbose_name': 'PushNotificationTopic', 'verbose_name_plural': 'PushNotificationTopics'},
        ),
    ]
