# Generated by Django 3.2 on 2022-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_auto_20220901_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationrecords',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
