# Generated by Django 3.2 on 2022-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_alter_pushnotificationrecords_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationrecords',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
