# Generated by Django 3.2 on 2022-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_alter_pushnotificationrecords_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationrecords',
            name='response_msg_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
