# Generated by Django 3.2 on 2022-09-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_scholarshiptestquestion_question_type'),
        ('courses', '0076_pushnotificationrecords_response_msg_id'),
    ]

    operations = [
    ]
