# Generated by Django 3.2 on 2022-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_merge_20220906_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshiptestquestion',
            name='question_type',
            field=models.CharField(choices=[('Text', 'Text'), ('MCQ', 'MCQ')], default='Text', max_length=20),
        ),
    ]
