# Generated by Django 3.2 on 2022-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0078_alter_scholarshiptestquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourplans',
            name='is_paid_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ourplans',
            name='trial_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ourplans',
            name='plan_name',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite'), ('Diamond', 'Diamond'), ('Trial2022', 'Trial2022')], max_length=20),
        ),
    ]
