# Generated by Django 3.2 on 2022-11-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0079_auto_20221013_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('test_type', models.CharField(choices=[('Pre', 'Pre'), ('Post', 'Post')], max_length=20)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
            ],
            options={
                'verbose_name': 'WebinarQuestionnaire',
                'verbose_name_plural': 'WebinarQuestionnaires',
            },
        ),
        migrations.CreateModel(
            name='WebinarQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('webinar_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.webinarquestionnaire')),
            ],
            options={
                'verbose_name': 'WebinarQuestion',
                'verbose_name_plural': 'WebinarQuestions',
            },
        ),
    ]
