# Generated by Django 3.2 on 2022-11-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0081_auto_20221117_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarquestionnaire',
            name='webinar',
        ),
        migrations.AddField(
            model_name='webinarquestionnaire',
            name='webinar',
            field=models.ManyToManyField(to='courses.Webinars'),
        ),
    ]
