# Generated by Django 3.2 on 2022-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_auto_20221117_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_for_middle_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
