# Generated by Django 3.2 on 2022-11-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0083_welcomevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('pdf_title', models.CharField(blank=True, max_length=70)),
                ('pdf_file', models.FileField(upload_to='files')),
                ('module_lang', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MyPdf',
                'verbose_name_plural': 'MyPdfs',
            },
        ),
    ]
