# Generated by Django 3.2 on 2022-12-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0084_mypdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortPushNotificationRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('topic', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField(blank=True, default='')),
                ('response_msg_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'CohortPushNotificationRecord',
                'verbose_name_plural': 'CohortPushNotificationRecords',
            },
        ),
    ]
