# Generated by Django 3.2 on 2022-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0084_mypdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='actionItem_completion_time',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='steps',
            name='step_completion_time',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
