# Generated by Django 3.2 on 2022-12-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0085_auto_20221211_2020'),
        ('courses', '0085_cohortpushnotificationrecords'),
    ]

    operations = [
    ]
