# Generated by Django 3.2 on 2022-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0083_cohort_is_for_middle_school'),
        ('courses', '0086_merge_20221212_0900'),
    ]

    operations = [
    ]
