# Generated by Django 3.2 on 2022-12-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0087_merge_20221216_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='is_for_middle_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
