# Generated by Django 3.2 on 2022-12-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0088_modules_is_for_middle_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemTypeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(max_length=500)),
                ('file_link', models.FileField(blank=True, upload_to='files')),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=dict)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionitem_type_table', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemTypeTable',
                'verbose_name_plural': 'ActionItemTypeTables',
                'ordering': ('sno',),
            },
        ),
    ]
