# Generated by Django 3.2 on 2023-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0089_actionitemtypetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemdiary',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemexitticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemexitticketoptions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemlinks',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitemtypetable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
