# Generated by Django 3.2 on 2023-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0090_auto_20230111_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitems',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
