# Generated by Django 3.2 on 2023-01-27 06:52

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0091_actionitems_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='hubspot_properties',
            field=models.JSONField(default=courses.models.hubspot_properties_dict),
        ),
    ]
