# Generated by Django 3.2 on 2023-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0091_actionitems_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='tot_steps',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='steps',
            name='is_backup_step',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
