# Generated by Django 3.2 on 2023-01-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0092_auto_20230129_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemTypeTableStep8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('criteria_question_head', models.CharField(blank=True, max_length=200, null=True)),
                ('criteria_question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionitem_type_table_step8', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemTypeTableStep8',
                'verbose_name_plural': 'ActionItemTypeTableStep8s',
                'ordering': ('sno',),
            },
        ),
    ]
