# Generated by Django 3.2 on 2023-01-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0092_webinars_hubspot_properties'),
        ('courses', '0093_actionitemtypetablestep8'),
    ]

    operations = [
    ]
