# Generated by Django 3.2 on 2023-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0094_merge_20230130_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_for_fast_track_program',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='is_for_fast_track_program',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
