# Generated by Django 3.2 on 2023-02-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0095_auto_20230202_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypdfs',
            name='is_for_middle_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
