# Generated by Django 3.2 on 2023-02-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0097_modules_allowed_display_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='allowed_display_timings',
            new_name='is_allowed_to_display_timings',
        ),
    ]
