# Generated by Django 3.2 on 2023-02-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0098_rename_allowed_display_timings_modules_is_allowed_to_display_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemGoogleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(max_length=500)),
                ('file_link', models.FileField(blank=True, upload_to='files')),
                ('description', models.TextField(blank=True)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Rating', 'Rating'), ('Other', 'Other')], default='Other', max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionitem_google_form', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemGoogleForm',
                'verbose_name_plural': 'ActionItemGoogleForms',
                'ordering': ('sno',),
            },
        ),
    ]
