# Generated by Django 3.2 on 2023-02-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0099_actionitemgoogleform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemgoogleform',
            name='type',
            field=models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Rating', 'Rating'), ('Star', 'Star'), ('Dropdown', 'Dropdown'), ('Text', 'Text')], default='Other', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ActionItemGoogleFormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('option', models.CharField(max_length=200)),
                ('option_type', models.CharField(blank=True, choices=[('MCQ', 'MCQ'), ('Dropdown', 'Dropdown')], default='MCQ', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_item_google_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_form_options', to='courses.actionitemgoogleform')),
            ],
            options={
                'verbose_name': 'ActionItemGoogleFormOption',
                'verbose_name_plural': 'ActionItemGoogleFormOptions',
                'ordering': ('sno',),
            },
        ),
    ]
