# Generated by Django 3.2 on 2023-03-27 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0101_alter_actionitemgoogleform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCohortID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cohort_id', to='courses.cohort')),
            ],
            options={
                'verbose_name': 'TestCohortID',
                'verbose_name_plural': 'TestCohortIDs',
            },
        ),
    ]
