# Generated by Django 3.2 on 2023-04-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0102_testcohortid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('sno', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionitem_framework', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemFramework',
                'verbose_name_plural': 'ActionItemFrameworks',
                'ordering': ('sno',),
            },
        ),
    ]
