# Generated by Django 3.2 on 2023-04-16 15:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0102_testcohortid'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemfiles',
            name='file_box_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='file_box_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='file_question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='actionitemfiles',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
