# Generated by Django 3.2 on 2023-04-16 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0103_auto_20230416_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitems',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
