# Generated by Django 3.2 on 2023-04-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0104_actionitemconnectwithotheractionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemconnectwithotheractionitem',
            name='secondary_action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_action_item', to='courses.actionitems'),
        ),
    ]
