# Generated by Django 3.2 on 2023-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0104_alter_actionitems_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemfiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
