# Generated by Django 3.2 on 2023-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0105_alter_actionitemfiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemfiles',
            name='file_uploadbox_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actionitemfiles',
            name='file_uploadbox_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
