# Generated by Django 3.2 on 2023-05-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0105_alter_actionitemconnectwithotheractionitem_secondary_action_item'),
        ('courses', '0107_actionitemfiles_file_box_link'),
    ]

    operations = [
    ]
