# Generated by Django 3.2 on 2023-05-25 13:00

import courses.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0108_merge_20230525_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemframework',
            name='questions',
            field=courses.models.NoSortJSONField(),
        ),
    ]
