# Generated by Django 3.2 on 2023-07-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0110_auto_20230706_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourplans',
            name='plan_name1',
        ),
        migrations.AlterField(
            model_name='ourplans',
            name='plan_name',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite'), ('Diamond', 'Diamond'), ('Trial2022', 'Trial2022'), ('FastTrack', 'FastTrack'), ('MiddleSchool', 'MiddleSchool')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PlanName',
        ),
    ]
