# Generated by Django 3.2 on 2023-07-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0110_actionitemdiary_is_linked_with_ai_comment'),
        ('courses', '0111_auto_20230710_1504'),
    ]

    operations = [
    ]
