# Generated by Django 3.2 on 2023-09-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0112_merge_20230711_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogvideos',
            name='is_for_fast_track',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
