# Generated by Django 3.2 on 2023-09-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0113_myblogvideos_is_for_fast_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogvideos',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
