# Generated by Django 3.2 on 2023-10-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0114_myblogvideos_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourplans',
            name='plan_name',
            field=models.CharField(choices=[('Community', 'Community'), ('Premium', 'Premium'), ('Elite', 'Elite'), ('Diamond', 'Diamond'), ('Trial2022', 'Trial2022'), ('FastTrack', 'FastTrack'), ('MiddleSchool', 'MiddleSchool'), ('JobCourse', 'JobCourse')], max_length=20),
        ),
    ]
