# Generated by Django 3.2 on 2023-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0116_myblogvideos_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('location', models.CharField(max_length=255)),
                ('job_portal_link', models.URLField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('job_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'JobPosting',
                'verbose_name_plural': 'JobPostings',
            },
        ),
    ]
