# Generated by Django 3.2 on 2023-11-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0099_student_age'),
        ('courses', '0117_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_to_display_specific_jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.company'),
        ),
    ]
