# Generated by Django 3.2 on 2023-11-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0119_alter_actionitemexitticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitemexitticket',
            name='sub_title_question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
