# Generated by Django 3.2 on 2023-07-12 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFOANextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Link', 'Link'), ('Text', 'Text')], default='MCQ', max_length=30)),
            ],
            options={
                'verbose_name': 'IFOANextQuestion',
                'verbose_name_plural': 'IFOANextQuestions',
            },
        ),
        migrations.CreateModel(
            name='IFOAPTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Text', 'Text')], default='MCQ', max_length=30)),
                ('question_category', models.CharField(choices=[('Realistic', 'Realistic'), ('Investigative', 'Investigative'), ('Artistic', 'Artistic'), ('Social', 'Social'), ('Enterprising', 'Enterprising'), ('Conventional', 'Conventional')], default='Realistic', max_length=30)),
            ],
            options={
                'verbose_name': 'IFOAPTQuestion',
                'verbose_name_plural': 'IFOAPTQuestions',
            },
        ),
        migrations.CreateModel(
            name='IFOAStudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('tax_id_code', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('how_did_you_know_us', models.CharField(blank=True, choices=[('Select', 'Select'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Tik Tok', 'Tik Tok'), ('Google', 'Google'), ('Friends', 'Friends'), ('Parents', 'Parents'), ('School', 'School'), ('Radio', 'Radio'), ('News Paper', 'News Paper'), ('Linkedin', 'Linkedin'), ('Other', 'Other')], max_length=50, null=True)),
                ('assessment_status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Started', 'Started'), ('Pending', 'Pending')], max_length=20, null=True)),
                ('certificate_link', models.FileField(blank=True, null=True, upload_to='')),
                ('clarity_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IFOAStudentDetail',
                'verbose_name_plural': 'IFOAStudentDetail',
            },
        ),
        migrations.CreateModel(
            name='IFOATest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test_title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IFOA', 'IFOA'), ('Other', 'Other')], default='IFOA', max_length=20)),
            ],
            options={
                'verbose_name': 'IFOATest',
                'verbose_name_plural': 'IFOATest',
            },
        ),
        migrations.CreateModel(
            name='IFOAStudentPTMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('ifoa_student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_student_detail', to='ifoa.ifoastudentdetail')),
                ('ifoa_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_test', to='ifoa.ifoatest')),
            ],
            options={
                'verbose_name': 'IFOAStudentPTMapper',
                'verbose_name_plural': 'IFOAStudentPTMappers',
            },
        ),
        migrations.CreateModel(
            name='IFOAStudentPTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('ifoa_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_ifoa_question', to='ifoa.ifoaptquestion')),
                ('ifoa_student_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_stu_mapper', to='ifoa.ifoastudentptmapper')),
            ],
            options={
                'verbose_name': 'IFOAStudentPTAnswer',
                'verbose_name_plural': 'IFOAStudentPTAnswers',
            },
        ),
        migrations.CreateModel(
            name='IFOAStudentNextQuestionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('ifoa_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_next_question_tracker', to='ifoa.ifoanextquestion')),
                ('ifoa_student_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_nextquestion_mapper', to='ifoa.ifoastudentdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IFOAPTQuestionMCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
                ('ifoa_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_qus_option', to='ifoa.ifoaptquestion')),
            ],
            options={
                'verbose_name': 'IFOAPTQuestionMCQOption',
                'verbose_name_plural': 'IFOAPTQuestionMCQOptions',
            },
        ),
        migrations.AddField(
            model_name='ifoaptquestion',
            name='ifoa_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_test_question', to='ifoa.ifoatest'),
        ),
        migrations.CreateModel(
            name='IFOANextQuestionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('ifoa_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_next_qus_video', to='ifoa.ifoanextquestion')),
            ],
            options={
                'verbose_name': 'IFOANextQuestionVideo',
                'verbose_name_plural': 'IFOANextQuestionVideos',
            },
        ),
        migrations.CreateModel(
            name='IFOANextQuestionMCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
                ('ifoa_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_next_qus_option', to='ifoa.ifoanextquestion')),
            ],
            options={
                'verbose_name': 'IFOANextQuestionMCQOption',
                'verbose_name_plural': 'IFOANextQuestionMCQOptions',
            },
        ),
        migrations.CreateModel(
            name='IFOANextQuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('link', models.CharField(max_length=200)),
                ('ifoa_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_next_qus_link', to='ifoa.ifoanextquestion')),
            ],
            options={
                'verbose_name': 'IFOANextQuestionLink',
                'verbose_name_plural': 'IFOANextQuestionLinks',
            },
        ),
        migrations.AddField(
            model_name='ifoanextquestion',
            name='ifoa_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_next_question_test', to='ifoa.ifoatest'),
        ),
    ]
