# Generated by Django 3.2 on 2023-07-18 05:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0002_ifoanextquestionoptionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFOAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Link', 'Link'), ('Text', 'Text')], default='MCQ', max_length=30)),
                ('ifoa_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question', to='ifoa.ifoatest')),
            ],
            options={
                'verbose_name': 'IFOAQuestion',
                'verbose_name_plural': 'IFOAQuestions',
            },
        ),
        migrations.CreateModel(
            name='IFOAQuestionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('link', models.CharField(max_length=200)),
                ('ifoa_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_link', to='ifoa.ifoaquestion')),
            ],
            options={
                'verbose_name': 'IFOAQuestionLink',
                'verbose_name_plural': 'IFOAQuestionLinks',
            },
        ),
        migrations.CreateModel(
            name='IFOAQuestionMCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
                ('ifoa_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_option', to='ifoa.ifoaquestion')),
            ],
            options={
                'verbose_name': 'IFOAQuestionMCQOption',
                'verbose_name_plural': 'IFOAQuestionMCQOptions',
            },
        ),
        migrations.CreateModel(
            name='IFOAQuestionMCQOptionLinkedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ifoa_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_linked', to='ifoa.ifoaquestion')),
                ('ifoa_question_mcq_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_option_linked', to='ifoa.ifoaquestionmcqoption')),
            ],
            options={
                'verbose_name': 'IFOAQuestionMCQOptionLinkedQuestion',
                'verbose_name_plural': 'IFOAQuestionMCQOptionLinkedQuestions',
            },
        ),
        migrations.CreateModel(
            name='IFOAQuestionOptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('video_link', models.CharField(max_length=200)),
                ('ifoa_question_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_option_link', to='ifoa.ifoaquestionmcqoption')),
            ],
            options={
                'verbose_name': 'IFOAQuestionOptionLink',
                'verbose_name_plural': 'IFOAQuestionOptionLinks',
            },
        ),
        migrations.CreateModel(
            name='IFOAStudentQuestionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.TextField(blank=True, null=True)),
                ('ifoa_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_tracker', to='ifoa.ifoaquestion')),
                ('ifoa_student_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_question_mapper', to='ifoa.ifoastudentdetail')),
            ],
            options={
                'verbose_name': 'IFOAStudentQuestionTracker',
                'verbose_name_plural': 'IFOAStudentQuestionTrackers',
            },
        ),
        migrations.RemoveField(
            model_name='ifoanextquestionlink',
            name='ifoa_next_question',
        ),
        migrations.RemoveField(
            model_name='ifoanextquestionmcqoption',
            name='ifoa_next_question',
        ),
        migrations.RemoveField(
            model_name='ifoanextquestionoptionlink',
            name='ifoa_next_question_option',
        ),
        migrations.RemoveField(
            model_name='ifoanextquestionvideo',
            name='ifoa_next_question',
        ),
        migrations.RemoveField(
            model_name='ifoastudentnextquestiontracker',
            name='ifoa_next_question',
        ),
        migrations.RemoveField(
            model_name='ifoastudentnextquestiontracker',
            name='ifoa_student_detail',
        ),
        migrations.AlterField(
            model_name='ifoastudentptanswer',
            name='ifoa_student_mapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_student_mapper', to='ifoa.ifoastudentptmapper'),
        ),
        migrations.DeleteModel(
            name='IFOANextQuestion',
        ),
        migrations.DeleteModel(
            name='IFOANextQuestionLink',
        ),
        migrations.DeleteModel(
            name='IFOANextQuestionMCQOption',
        ),
        migrations.DeleteModel(
            name='IFOANextQuestionOptionLink',
        ),
        migrations.DeleteModel(
            name='IFOANextQuestionVideo',
        ),
        migrations.DeleteModel(
            name='IFOAStudentNextQuestionTracker',
        ),
    ]
