# Generated by Django 3.2 on 2023-07-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0003_auto_20230718_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifoaquestionmcqoptionlinkedquestion',
            name='ifoa_question_mcq_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ifoa_question_option_linked', to='ifoa.ifoaquestionmcqoption'),
        ),
    ]
