# Generated by Django 3.2 on 2023-07-25 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0004_alter_ifoaquestionmcqoptionlinkedquestion_ifoa_question_mcq_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifoaquestion',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifoastudentdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ifoastudentdetail',
            name='how_did_you_know_us',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Tik Tok', 'Tik Tok'), ('Google', 'Google'), ('Friends', 'Friends'), ('Parents', 'Parents'), ('School', 'School'), ('Radio', 'Radio'), ('News Paper', 'News Paper'), ('Linkedin', 'Linkedin'), ('Other', 'Other')], default='', max_length=50, null=True),
        ),
    ]
