# Generated by Django 3.2 on 2023-08-02 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0005_auto_20230725_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFOAOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('otp', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IFOAOTP',
                'verbose_name_plural': 'IFOAOTP',
            },
        ),
        migrations.AddField(
            model_name='ifoastudentdetail',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ifoastudentdetail',
            name='how_did_you_know_us',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Tik Tok', 'Tik Tok'), ('Google', 'Google'), ('Friends', 'Friends'), ('Parents', 'Parents'), ('School', 'School'), ('Radio', 'Radio'), ('News Paper', 'News Paper'), ('Linkedin', 'Linkedin'), ('Sito IFOA', 'Sito IFOA'), ('Other', 'Other')], default='', max_length=50, null=True),
        ),
    ]
