# Generated by Django 3.2 on 2023-08-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0006_auto_20230802_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IFOAOTP',
        ),
    ]
