# Generated by Django 3.2 on 2023-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifoa', '0007_delete_ifoaotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifoastudentdetail',
            name='finalità_di_marketing',
            field=models.CharField(blank=True, default='Yes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ifoastudentdetail',
            name='informativa_sulla_privacy',
            field=models.CharField(blank=True, default='Yes', max_length=100, null=True),
        ),
    ]
