# Generated by Django 3.2 on 2023-04-13 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCentreOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ApprovedCentreOption',
                'verbose_name_plural': 'ApprovedCentreOptions',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session_id', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, choices=[('Università telematica Pegaso', 'Università telematica Pegaso'), ('Università telematica San Raffaele', 'Università telematica San Raffaele'), ('Università Mercatorum', 'Università Mercatorum')], max_length=100, null=True)),
                ('year_of_enrollment', models.CharField(max_length=100)),
                ('are_you_taking_this_test_at_a_contracted_center', models.BooleanField(default=False)),
                ('test_at_a_contracted_center_other', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Started', 'Started'), ('Pending', 'Pending')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'StudentDetail',
                'verbose_name_plural': 'StudentDetails',
            },
        ),
        migrations.CreateModel(
            name='UnipagesoStudentPTMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('rising_test_result', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('student_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_ptest_mapper', to='unipegaso.studentdetail')),
            ],
            options={
                'verbose_name': 'UnipagesoStudentPTMapper',
                'verbose_name_plural': 'UnipagesoStudentPTMappers',
            },
        ),
        migrations.CreateModel(
            name='UnipegasoActionItemsNextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sno', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Link', 'Link'), ('Text', 'Text')], default='MCQ', max_length=30)),
            ],
            options={
                'verbose_name': 'UnipegasoActionItemsNextQuestion',
                'verbose_name_plural': 'UnipegasoActionItemsNextQuestions',
            },
        ),
        migrations.CreateModel(
            name='UnipegasoActionItemsNextQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
                ('unipegaso_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_next_option', to='unipegaso.unipegasoactionitemsnextquestion')),
            ],
            options={
                'verbose_name': 'UnipegasoActionItemsNextQuestionOption',
                'verbose_name_plural': 'UnipegasoActionItemsNextQuestionOptions',
            },
        ),
        migrations.CreateModel(
            name='UniPegasoActionItemsPTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Text', 'Text')], default='MCQ', max_length=30)),
                ('question_category', models.CharField(choices=[('Realistic', 'Realistic'), ('Investigative', 'Investigative'), ('Artistic', 'Artistic'), ('Social', 'Social'), ('Enterprising', 'Enterprising'), ('Conventional', 'Conventional')], default='Realistic', max_length=30)),
            ],
            options={
                'verbose_name': 'UniPegasoActionItemsPTQuestion',
                'verbose_name_plural': 'UniPegasoActionItemsPTQuestions',
            },
        ),
        migrations.CreateModel(
            name='UnipegasoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('action_item_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('PT', 'PT'), ('Other', 'Other')], default='PT', max_length=20)),
            ],
            options={
                'verbose_name': 'UnipegasoTest',
                'verbose_name_plural': 'UnipegasoTests',
            },
        ),
        migrations.CreateModel(
            name='UnipegasoVideoOptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('link', models.CharField(max_length=100)),
                ('unipegaso_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_option_video_link', to='unipegaso.unipegasoactionitemsnextquestionoption')),
            ],
            options={
                'verbose_name': 'UnipegasoVideoOptionLink',
                'verbose_name_plural': 'UnipegasoVideoOptionLinks',
            },
        ),
        migrations.CreateModel(
            name='UnipegasoStudentPTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('unipegaso_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_unipegaso_question', to='unipegaso.unipegasoactionitemsptquestion')),
                ('unipegaso_student_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_stu_mapper', to='unipegaso.unipagesostudentptmapper')),
            ],
            options={
                'verbose_name': 'UnipegasoStudentPTAnswer',
                'verbose_name_plural': 'UnipegasoStudentPTAnswers',
            },
        ),
        migrations.AddField(
            model_name='unipegasoactionitemsptquestion',
            name='unipegaso_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_test_question', to='unipegaso.unipegasotest'),
        ),
        migrations.CreateModel(
            name='UnipegasoActionItemsNextQuestionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('video_link', models.CharField(max_length=200)),
                ('unipegaso_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_next_videos', to='unipegaso.unipegasoactionitemsnextquestion')),
            ],
            options={
                'verbose_name': 'UnipegasoActionItemsNextQuestionVideo',
                'verbose_name_plural': 'UnipegasoActionItemsNextQuestionVideos',
            },
        ),
        migrations.AddField(
            model_name='unipegasoactionitemsnextquestion',
            name='unipegaso_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_test', to='unipegaso.unipegasotest'),
        ),
        migrations.CreateModel(
            name='UniPegasoActionItemPTOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('option', models.CharField(max_length=100)),
                ('unipegaso_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_qus_option', to='unipegaso.unipegasoactionitemsptquestion')),
            ],
            options={
                'verbose_name': 'UniPegasoActionItemPTOption',
                'verbose_name_plural': 'UniPegasoActionItemPTOptions',
            },
        ),
        migrations.AddField(
            model_name='unipagesostudentptmapper',
            name='unipegaso_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_ptest_mapper', to='unipegaso.unipegasotest'),
        ),
        migrations.CreateModel(
            name='UnipagesoStudentNextQuestionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('student_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail_nextquestion_mapper', to='unipegaso.studentdetail')),
                ('unipegaso_ai_next_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unipegaso_next_question_tracker', to='unipegaso.unipegasoactionitemsnextquestion')),
            ],
            options={
                'verbose_name': 'UnipagesoStudentNextQuestionTracker',
                'verbose_name_plural': 'UnipagesoStudentNextQuestionTrackers',
            },
        ),
    ]
