# Generated by Django 3.2 on 2023-04-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unipegaso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedcentreoption',
            options={'verbose_name': '1_ApprovedCentreOption', 'verbose_name_plural': '1_ApprovedCentreOptions'},
        ),
        migrations.AlterModelOptions(
            name='studentdetail',
            options={'verbose_name': '9.0_StudentDetail', 'verbose_name_plural': '9.0_StudentDetails'},
        ),
        migrations.AlterModelOptions(
            name='unipagesostudentnextquestiontracker',
            options={'verbose_name': '9.3_UnipagesoStudentNextQuestionTracker', 'verbose_name_plural': '9.3_UnipagesoStudentNextQuestionTrackers'},
        ),
        migrations.AlterModelOptions(
            name='unipagesostudentptmapper',
            options={'verbose_name': '9.1_UnipagesoStudentPTMapper', 'verbose_name_plural': '9.1_UnipagesoStudentPTMappers'},
        ),
        migrations.AlterModelOptions(
            name='unipegasoactionitemptoption',
            options={'verbose_name': '4_UniPegasoActionItemPTOption', 'verbose_name_plural': '4_UniPegasoActionItemPTOptions'},
        ),
        migrations.AlterModelOptions(
            name='unipegasoactionitemsnextquestion',
            options={'verbose_name': '5_UnipegasoActionItemsNextQuestion', 'verbose_name_plural': '5_UnipegasoActionItemsNextQuestions'},
        ),
        migrations.AlterModelOptions(
            name='unipegasoactionitemsnextquestionoption',
            options={'verbose_name': '6_UnipegasoActionItemsNextQuestionOption', 'verbose_name_plural': '6_UnipegasoActionItemsNextQuestionOptions'},
        ),
        migrations.AlterModelOptions(
            name='unipegasoactionitemsnextquestionvideo',
            options={'verbose_name': '8_UnipegasoActionItemsNextQuestionVideo', 'verbose_name_plural': '8_UnipegasoActionItemsNextQuestionVideos'},
        ),
        migrations.AlterModelOptions(
            name='unipegasoactionitemsptquestion',
            options={'verbose_name': '3_UniPegasoActionItemsPTQuestion', 'verbose_name_plural': '3_UniPegasoActionItemsPTQuestions'},
        ),
        migrations.AlterModelOptions(
            name='unipegasostudentptanswer',
            options={'verbose_name': '9.2_UnipegasoStudentPTAnswer', 'verbose_name_plural': '9.2_UnipegasoStudentPTAnswers'},
        ),
        migrations.AlterModelOptions(
            name='unipegasotest',
            options={'verbose_name': '2_UnipegasoTest', 'verbose_name_plural': '2_UnipegasoTests'},
        ),
        migrations.AlterModelOptions(
            name='unipegasovideooptionlink',
            options={'verbose_name': '7_UnipegasoVideoOptionLink', 'verbose_name_plural': '7_UnipegasoVideoOptionLinks'},
        ),
    ]
