# Generated by Django 3.2 on 2023-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipegaso', '0002_auto_20230413_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unipagesostudentnextquestiontracker',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unipegasostudentptanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
