# Generated by Django 3.2 on 2023-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipegaso', '0003_auto_20230413_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unipegasotest',
            name='type',
            field=models.CharField(choices=[('PT', 'PT'), ('UniMercatorum', 'UniMercatorum'), ('UTSanRaffaele', 'UTSanRaffaele'), ('Other', 'Other')], default='PT', max_length=20),
        ),
    ]
