# Generated by Django 3.2 on 2023-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unipegaso', '0004_alter_unipegasotest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedcentreoption',
            name='option_type',
            field=models.CharField(choices=[('UniPegaso', 'UniPegaso'), ('Mercatorum', 'Mercatorum'), ('Other', 'Other')], default='UniPegaso', max_length=100),
        ),
    ]
