# Generated by Django 3.2 on 2021-07-06 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_auto_20210706_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItemTracker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('Action_item_track_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('ActionItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_track', to='courses.actionitems')),
            ],
            options={
                'verbose_name': 'ActionItemTracker',
                'verbose_name_plural': 'ActionItemTracker',
            },
        ),
        migrations.CreateModel(
            name='StudentCohortMapper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('stu_cohort_map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohortMapID', to='courses.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuMapID', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentCohortMapper',
                'verbose_name_plural': 'StudentCohortMapper',
            },
        ),
        migrations.CreateModel(
            name='StudentActionItemLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('is_done', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_link', to='courses.actionitemlinks')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_link_track', to='student.actionitemtracker')),
            ],
            options={
                'verbose_name': 'StudentActionItemLinks',
                'verbose_name_plural': 'StudentActionItemLinks',
            },
        ),
        migrations.CreateModel(
            name='StudentActionItemFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='stu_files')),
                ('is_done', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_file', to='courses.actionitemfiles')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_file_track', to='student.actionitemtracker')),
            ],
            options={
                'verbose_name': 'StudentActionItemFiles',
                'verbose_name_plural': 'StudentActionItemFiles',
            },
        ),
        migrations.CreateModel(
            name='StudentActionItemDairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_done', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_dairy', to='courses.actionitemfiles')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_dairy_track', to='student.actionitemtracker')),
            ],
            options={
                'verbose_name': 'StudentActionItemDairy',
                'verbose_name_plural': 'StudentActionItemDairy',
            },
        ),
        migrations.CreateModel(
            name='StepTracker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('step_track_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('step_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_status_id', to='courses.step_status')),
                ('stu_cohort_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_cohort_map', to='student.studentcohortmapper')),
            ],
            options={
                'verbose_name': 'StepTracker',
                'verbose_name_plural': 'StepTracker',
            },
        ),
        migrations.AddField(
            model_name='actionitemtracker',
            name='step_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_tracker', to='student.steptracker'),
        ),
    ]
