# Generated by Django 3.2 on 2021-07-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentactionitemdairy',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='studentactionitemfiles',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='studentactionitemlinks',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
