# Generated by Django 3.2 on 2021-07-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210707_0608'),
        ('student', '0003_alter_studentactionitemdairy_action_item_dairy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepTracker',
            new_name='CohortStepTracker',
        ),
        migrations.RenameModel(
            old_name='ActionItemTracker',
            new_name='StudentActionItemTracker',
        ),
        migrations.AlterModelOptions(
            name='cohortsteptracker',
            options={'verbose_name': 'CohortStepTracker', 'verbose_name_plural': 'CohortStepTracker'},
        ),
    ]
