# Generated by Django 3.2 on 2021-07-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentactionitemtracker_step_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactionitemtracker',
            name='is_completed',
        ),
    ]
