# Generated by Django 3.2 on 2021-07-15 14:46

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentactionitemtracker_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactionitemfiles',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=student.models.content_file_name),
        ),
    ]
