# Generated by Django 3.2 on 2021-07-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210720_0415'),
        ('student', '0007_alter_studentactionitemfiles_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_diary', to='courses.actionitemdiary')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_diary_track', to='student.studentactionitemtracker')),
            ],
            options={
                'verbose_name': 'StudentActionItemDiary',
                'verbose_name_plural': 'StudentActionItemDiary',
            },
        ),
        migrations.DeleteModel(
            name='StudentActionItemDairy',
        ),
    ]
