# Generated by Django 3.2 on 2021-07-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('isread', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_notifications', to='courses.notification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student_Notification',
                'verbose_name_plural': 'Student_Notifications',
            },
        ),
    ]
