# Generated by Django 3.2 on 2021-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_stu_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_notification',
            name='type',
            field=models.CharField(blank=True, default='General', max_length=15, null=True),
        ),
    ]
