# Generated by Django 3.2 on 2021-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_stu_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
