# Generated by Django 3.2 on 2021-08-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0038_auto_20210829_1309'),
        ('student', '0014_todos_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsPlanMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentPlans', to='courses.ourplans')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentPlans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentsPlanMapper',
                'verbose_name_plural': 'StudentsPlanMapper',
            },
        ),
    ]
