# Generated by Django 3.2 on 2021-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_studentsplanmapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsplanmapper',
            name='plan_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='en-us', max_length=20),
        ),
    ]
