# Generated by Django 3.2 on 2021-09-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_studentsplanmapper_plan_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcohortmapper',
            name='stu_cohort_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentsplanmapper',
            name='plan_lang',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
    ]
