# Generated by Django 3.2 on 2021-09-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20210901_1042'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='studentactionitemtracker',
            order_with_respect_to='ActionItem',
        ),
    ]
