# Generated by Django 3.2 on 2021-09-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_studentactionitemtracker_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentactionitemtracker',
            options={'ordering': ['ActionItem__action_sno'], 'verbose_name': 'ActionItemTracker', 'verbose_name_plural': 'ActionItemTracker'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='studentactionitemtracker',
            order_with_respect_to=None,
        ),
    ]
