# Generated by Django 3.2 on 2021-09-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20210908_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohortsteptracker',
            options={'ordering': ['step_status_id__step__step_sno'], 'verbose_name': 'CohortStepTracker', 'verbose_name_plural': 'CohortStepTracker'},
        ),
    ]
