# Generated by Django 3.2 on 2021-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_cohortsteptracker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactionitemdiary',
            name='cohort_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentactionitemdiary',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentactionitemdiary',
            name='step_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
