# Generated by Django 3.2 on 2021-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentactionitemtracker',
            options={'ordering': ['ActionItem__action_sno'], 'verbose_name': 'StudentActionItemTracker', 'verbose_name_plural': 'StudentActionItemTracker'},
        ),
        migrations.AddField(
            model_name='cohortsteptracker',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentactionitemtracker',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
