# Generated by Django 3.2 on 2021-11-29 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210915_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsplanmapper',
            name='is_trial_activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studentsplanmapper',
            name='trail_days',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name='studentsplanmapper',
            name='trial_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsplanmapper',
            name='trial_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsplanmapper',
            name='trial_type',
            field=models.CharField(blank=True, choices=[('Premium', 'Premium'), ('Elite', 'Elite'), ('Premium_to_elite', 'Premium_to_elite')], default='', max_length=20, null=True),
        ),
    ]
