# Generated by Django 3.2 on 2021-11-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20211129_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsplanmapper',
            name='is_trial_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentsplanmapper',
            name='trial_type',
            field=models.CharField(blank=True, choices=[('Community_to_Premium', 'Community_to_Premium'), ('Community_to_Elite', 'Community_to_Elite'), ('Premium_to_Elite', 'Premium_to_Elite')], default='', max_length=20, null=True),
        ),
    ]
