# Generated by Django 3.2 on 2021-12-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_actionitemexitticket_actionitemexitticketoptions'),
        ('student', '0025_auto_20211129_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemExitTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_exit_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_exit_ticket', to='courses.actionitemexitticket')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_exit_ticket_track', to='student.studentactionitemtracker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
