# Generated by Django 3.2 on 2021-12-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_studentactionitemexitticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentactionitemdiary',
            options={'ordering': ('action_item_diary__sno',), 'verbose_name': 'StudentActionItemDiary', 'verbose_name_plural': 'StudentActionItemDiary'},
        ),
        migrations.AlterModelOptions(
            name='studentactionitemexitticket',
            options={'ordering': ['action_item_exit_ticket__sno'], 'verbose_name': 'StudentActionItemExitTicket', 'verbose_name_plural': 'StudentActionItemExitTickets'},
        ),
        migrations.AlterModelOptions(
            name='studentactionitemfiles',
            options={'ordering': ('action_item_file__sno',), 'verbose_name': 'StudentActionItemFiles', 'verbose_name_plural': 'StudentActionItemFiles'},
        ),
        migrations.AlterModelOptions(
            name='studentactionitemlinks',
            options={'ordering': ('action_item_link__sno',), 'verbose_name': 'StudentActionItemLinks', 'verbose_name_plural': 'StudentActionItemLinks'},
        ),
    ]
