# Generated by Django 3.2 on 2022-03-11 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_personalitytest_personalitytestquestion_ptquestionoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0028_studentcohortmapper_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPersonalityTestMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('last_answered', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('personality_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_ptest_mapper', to='courses.personalitytest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_ptest_mapper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentPersonalityTestMapper',
                'verbose_name_plural': 'StudentsPersonalityTestMapper',
            },
        ),
        migrations.CreateModel(
            name='StudentPersonalityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('pt_option', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('pt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_ptest_question', to='courses.personalitytestquestion')),
                ('stu_pt_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_ptest', to='student.studentpersonalitytestmapper')),
            ],
            options={
                'verbose_name': 'StudentPersonalityTest',
                'verbose_name_plural': 'StudentsPersonalityTests',
            },
        ),
    ]
