# Generated by Django 3.2 on 2022-03-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_studentpersonalitytest_studentpersonalitytestmapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpersonalitytest',
            old_name='pt_option',
            new_name='pt_answer',
        ),
    ]
