# Generated by Django 3.2 on 2022-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_rename_pt_option_studentpersonalitytest_pt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalitytestmapper',
            name='lang_code',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
    ]
