# Generated by Django 3.2 on 2022-07-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_scholarshiptestquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarShipStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.CharField(blank=True, max_length=250, null=True)),
                ('scholarship_test_que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.scholarshiptestquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentcohortmapper')),
            ],
            options={
                'verbose_name': 'ScholarShipStudentAnswer',
                'verbose_name_plural': 'ScholarShipStudentAnswers',
            },
        ),
    ]
