# Generated by Django 3.2 on 2022-07-22 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0064_scholarshiptestquestion'),
        ('student', '0034_alter_scholarshipstudentanswer_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScholarShipTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.CharField(blank=True, max_length=250, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('sship_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_sship_question', to='courses.scholarshiptestquestion')),
            ],
            options={
                'verbose_name': 'StudentScholarShipTest',
                'verbose_name_plural': 'StudentsScholarShipTest',
            },
        ),
        migrations.CreateModel(
            name='StudentScholarshipTestMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('last_answered', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('scholarship_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_sship_mapper', to='courses.scholarshiptestquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_sship_mapper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentScholarshipTestMapper',
                'verbose_name_plural': 'StudentsScholarshipTestMapper',
            },
        ),
        migrations.DeleteModel(
            name='ScholarShipStudentAnswer',
        ),
        migrations.DeleteModel(
            name='ScholarshipTestQuestion',
        ),
        migrations.AddField(
            model_name='studentscholarshiptest',
            name='stu_sship_mapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_sship', to='student.studentscholarshiptestmapper'),
        ),
    ]
