# Generated by Django 3.2 on 2022-07-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0035_auto_20220722_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscholarshiptest',
            name='stu_sship_mapper',
        ),
        migrations.AddField(
            model_name='studentscholarshiptest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sship', to='userauth.person'),
            preserve_default=False,
        ),
    ]
