# Generated by Django 3.2 on 2022-07-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0063_studentparentsdetail'),
        ('courses', '0065_auto_20220726_1108'),
        ('student', '0036_auto_20220722_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWebinarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('is_webinar_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_webinar_record', to='userauth.student')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_webinar_record', to='courses.webinars')),
            ],
            options={
                'verbose_name': 'StudentWebinarRecord',
                'verbose_name_plural': 'StudentWebinarRecord2',
            },
        ),
        migrations.CreateModel(
            name='StudentPCTORecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('pcto_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('pcto_hour_source', models.CharField(blank=True, choices=[('Future-lab', 'Future-lab'), ('Webinar', 'Webinar')], default='Webinar', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_pcto_record', to='userauth.student')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_pcto_record', to='student.studentwebinarrecord')),
            ],
            options={
                'verbose_name': 'StudentPCTORecord',
                'verbose_name_plural': 'StudentPCTORecords',
            },
        ),
    ]
