# Generated by Django 3.2 on 2022-07-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_studentpctorecord_studentwebinarrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentwebinarrecord',
            options={'verbose_name': 'StudentWebinarRecord', 'verbose_name_plural': 'StudentWebinarRecords'},
        ),
    ]
