# Generated by Django 3.2 on 2022-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_alter_studentwebinarrecord_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwebinarrecord',
            name='is_webinar_completed',
        ),
        migrations.AddField(
            model_name='studentwebinarrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Attendant', 'Attendant')], default='Registered', max_length=50),
        ),
    ]
