# Generated by Django 3.2 on 2022-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20220726_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentscholarshiptestmapper',
            old_name='scholarship_test',
            new_name='scholarship_question',
        ),
        migrations.RemoveField(
            model_name='studentscholarshiptestmapper',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studentscholarshiptestmapper',
            name='lang_code',
        ),
        migrations.RemoveField(
            model_name='studentscholarshiptestmapper',
            name='last_answered',
        ),
        migrations.AddField(
            model_name='studentscholarshiptestmapper',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
