# Generated by Django 3.2 on 2022-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20220728_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwebinarrecord',
            name='seat_reserve',
            field=models.BooleanField(default=False),
        ),
    ]
