# Generated by Django 3.2 on 2022-08-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_studentwebinarrecord_seat_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscholarshiptestmapper',
            name='scholarship_question',
        ),
        migrations.RemoveField(
            model_name='studentscholarshiptestmapper',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudentScholarShipTest',
        ),
        migrations.DeleteModel(
            name='StudentScholarshipTestMapper',
        ),
    ]
