# Generated by Django 3.2 on 2022-08-04 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0068_scholarshiptest_scholarshiptestquestion'),
        ('student', '0042_auto_20220804_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScholarshipTestMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('last_answered', models.IntegerField(blank=True, default=0, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('scholarship_test', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test_mapper', to='courses.scholarshiptest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test_mapper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentScholarshipTestMapper',
                'verbose_name_plural': 'StudentsScholarshipTestMapper',
            },
        ),
        migrations.CreateModel(
            name='StudentScholarShipTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('scholarshipTest_answer', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('scholarshipTest_question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test', to='courses.scholarshiptestquestion')),
                ('stu_scholarshipTest_mapper', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test', to='student.studentscholarshiptestmapper')),
            ],
            options={
                'verbose_name': 'StudentScholarShipTest',
                'verbose_name_plural': 'StudentsScholarShipTest',
            },
        ),
    ]
