# Generated by Django 3.2 on 2022-08-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_auto_20220804_1427'),
        ('student', '0043_studentscholarshiptest_studentscholarshiptestmapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscholarshiptest',
            name='scholarshipTest_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test_ques', to='courses.scholarshiptestquestion'),
        ),
        migrations.AlterField(
            model_name='studentscholarshiptest',
            name='stu_scholarshipTest_mapper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stu_scholarship_test_ques', to='student.studentscholarshiptestmapper'),
        ),
    ]
