# Generated by Django 3.2 on 2022-08-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_auto_20220804_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwebinarrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Attended', 'Attended')], default='Registered', max_length=50),
        ),
    ]
