# Generated by Django 3.2 on 2022-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_alter_studentwebinarrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscholarshiptestmapper',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Decline', 'Decline')], default='Applied', max_length=20),
        ),
    ]
