# Generated by Django 3.2 on 2022-08-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_studentscholarshiptestmapper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpctorecord',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_pcto_record', to='student.studentwebinarrecord'),
        ),
        migrations.AlterField(
            model_name='studentscholarshiptestmapper',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Applied', max_length=20),
        ),
    ]
