# Generated by Django 3.2 on 2022-09-05 12:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_auto_20220831_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpctorecord',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_pcto_record', to='student.studentwebinarrecord'),
        ),
    ]
