# Generated by Django 3.2 on 2022-09-08 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0048_alter_studentpctorecord_webinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemDiaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_comments', to=settings.AUTH_USER_MODEL)),
                ('student_actions_item_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_student_actions_item_diary', to='student.studentactionitemdiary')),
            ],
            options={
                'verbose_name': 'StudentActionItemDiaryComment',
                'verbose_name_plural': 'StudentActionItemDiaryComments',
                'ordering': ('created_at',),
            },
        ),
    ]
