# Generated by Django 3.2 on 2022-09-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_studentactionitemdiarycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactionitemdiarycomment',
            name='comment',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
