# Generated by Django 3.2 on 2022-09-19 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0050_alter_studentactionitemdiarycomment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalitytestmapper',
            name='is_created_by_loggedin_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentpersonalitytestmapper',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentpersonalitytestmapper',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_ptest_mapper', to=settings.AUTH_USER_MODEL),
        ),
    ]
