# Generated by Django 3.2 on 2022-10-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_auto_20220919_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsplanmapper',
            old_name='is_trial_activated',
            new_name='is_trial_active',
        ),
    ]
