# Generated by Django 3.2 on 2022-11-02 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_rename_is_trial_activated_studentsplanmapper_is_trial_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortsteptracker',
            name='last_commented_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
