# Generated by Django 3.2 on 2022-11-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0080_webinarquestion_webinarquestionnaire'),
        ('student', '0053_cohortsteptracker_last_commented_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWebinarMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test_mapper', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar', to='courses.webinars')),
                ('webinar_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test_mapper', to='courses.webinarquestionnaire')),
            ],
            options={
                'verbose_name': 'StudentWebinarMapper',
                'verbose_name_plural': 'StudentWebinarsMapper',
            },
        ),
        migrations.CreateModel(
            name='StudentWebinarAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('webinar_answer', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('stu_webinar_mapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test', to='student.studentwebinarmapper')),
                ('webinar_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_question', to='courses.webinarquestion')),
            ],
            options={
                'verbose_name': 'StudentWebinarAnswer',
                'verbose_name_plural': 'StudentWebinarAnswers',
            },
        ),
    ]
