# Generated by Django 3.2 on 2022-11-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_studentwebinaranswer_studentwebinarmapper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentwebinarmapper',
            old_name='webinar_ques',
            new_name='webinar_questionnaire',
        ),
    ]
