# Generated by Django 3.2 on 2022-11-23 07:09

import builtins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_auto_20221117_0454'),
        ('student', '0055_rename_webinar_ques_studentwebinarmapper_webinar_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwebinaranswer',
            name='stu_webinar_mapper',
        ),
        migrations.AddField(
            model_name='studentwebinaranswer',
            name='stu_webinar_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test', to='student.studentwebinarrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentwebinarrecord',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentwebinarrecord',
            name='lang_code',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20),
        ),
        migrations.AddField(
            model_name='studentwebinarrecord',
            name='webinar_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test_mapper', to='courses.webinarquestionnaire'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentWebinarMapper',
        ),
    ]
