# Generated by Django 3.2 on 2022-11-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0056_auto_20221123_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwebinarrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Attended', 'Attended')], default='', max_length=50),
        ),
    ]
