# Generated by Django 3.2 on 2022-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_alter_studentwebinarrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwebinarrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Attended', 'Attended'), ('Question', 'Question')], default='Question', max_length=50),
        ),
    ]
