# Generated by Django 3.2 on 2022-11-23 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0082_auto_20221117_0454'),
        ('student', '0058_alter_studentwebinarrecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwebinaranswer',
            name='stu_webinar_record',
        ),
        migrations.RemoveField(
            model_name='studentwebinarrecord',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studentwebinarrecord',
            name='lang_code',
        ),
        migrations.RemoveField(
            model_name='studentwebinarrecord',
            name='webinar_questionnaire',
        ),
        migrations.AlterField(
            model_name='studentwebinarrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('Attended', 'Attended')], default='Registered', max_length=50),
        ),
        migrations.CreateModel(
            name='StudentWebinarMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], default='it', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test_mapper', to=settings.AUTH_USER_MODEL)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar', to='courses.webinars')),
                ('webinar_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test_mapper', to='courses.webinarquestionnaire')),
            ],
            options={
                'verbose_name': 'StudentWebinarMapper',
                'verbose_name_plural': 'StudentWebinarsMapper',
            },
        ),
        migrations.AddField(
            model_name='studentwebinaranswer',
            name='stu_webinar_mapper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_webinar_test', to='student.studentwebinarmapper'),
            preserve_default=False,
        ),
    ]
