# Generated by Django 3.2 on 2022-12-09 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_auto_20221123_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortsteptracker',
            name='last_commented_date_time',
        ),
        migrations.CreateModel(
            name='CohortStepTrackerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('last_commented_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cohort_step_tracker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_step_tracker_details', to='student.cohortsteptracker')),
            ],
            options={
                'verbose_name': 'CohortStepTrackerDetail',
                'verbose_name_plural': 'CohortStepTrackerDetails',
            },
        ),
    ]
