# Generated by Django 3.2 on 2022-12-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0089_actionitemtypetable'),
        ('student', '0060_auto_20221209_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemTypeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.JSONField(default=dict)),
                ('is_completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_type_table_track', to='student.studentactionitemtracker')),
                ('action_item_type_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_type_table', to='courses.actionitemtypetable')),
            ],
            options={
                'verbose_name': 'StudentActionItemTypeTable',
                'verbose_name_plural': 'StudentActionItemTypeTables',
                'ordering': ['action_item_type_table__sno'],
            },
        ),
    ]
