# Generated by Django 3.2 on 2023-01-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='awareness_score',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='confidence_score',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='curiosity_score',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
