# Generated by Django 3.2 on 2023-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_auto_20230105_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortsteptrackerdetails',
            name='step_completion',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
