# Generated by Django 3.2 on 2023-01-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0075_merge_20221216_0853'),
        ('student', '0063_cohortsteptrackerdetails_step_completion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProgress',
            new_name='StudentProgressDetail',
        ),
        migrations.AlterModelOptions(
            name='studentprogressdetail',
            options={'verbose_name': 'StudentProgressDetail', 'verbose_name_plural': 'StudentsProgressDetail'},
        ),
    ]
