# Generated by Django 3.2 on 2023-01-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_auto_20230106_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortsteptrackerdetails',
            name='step_completion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogressdetail',
            name='awareness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogressdetail',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogressdetail',
            name='curiosity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprogressdetail',
            name='endurance_score',
            field=models.IntegerField(default=0),
        ),
    ]
