# Generated by Django 3.2 on 2023-01-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_alter_studentactionitemtypetable_answer'),
        ('student', '0065_auto_20230106_0557'),
    ]

    operations = [
    ]
