# Generated by Django 3.2 on 2023-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_alter_studentpctorecord_pcto_hour_source'),
        ('student', '0068_studentfaq'),
    ]

    operations = [
    ]
