# Generated by Django 3.2 on 2023-02-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0069_merge_20230217_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpctorecord',
            name='pcto_hour_source',
            field=models.CharField(blank=True, choices=[('Future-lab', 'Future-lab'), ('Webinar', 'Webinar'), ('Course-1', 'Conoscenza di sé e apertura a nuove prospettive'), ('Course-2', 'Conoscenza del mondo universitario/ITS')], default='Webinar', max_length=50),
        ),
    ]
