# Generated by Django 3.2 on 2023-02-23 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0099_actionitemgoogleform'),
        ('student', '0070_alter_studentpctorecord_pcto_hour_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemGoogleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_completed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('action_item_google_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_action_item_google_form', to='courses.actionitemgoogleform')),
                ('action_item_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_item_google_form_track', to='student.studentactionitemtracker')),
            ],
            options={
                'verbose_name': 'StudentActionItemGoogleForm',
                'verbose_name_plural': 'StudentActionItemGoogleForms',
                'ordering': ['action_item_google_form__sno'],
            },
        ),
    ]
