# Generated by Django 3.2 on 2023-03-13 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0071_studentactionitemgoogleform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificate_download', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CertificateDownload',
                'verbose_name_plural': 'CertificateDownloads',
            },
        ),
    ]
