# Generated by Django 3.2 on 2023-03-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0080_student_student_channel'),
        ('student', '0073_remove_certificatedownload_download_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatedownload',
            old_name='downloaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='certificatedownload',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='certificatedownload',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificatedownload',
            name='modified_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='certificatedownload',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificate_download', to='userauth.student'),
        ),
    ]
