# Generated by Django 3.2 on 2023-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0074_auto_20230314_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpctorecord',
            name='pcto_hour_source',
            field=models.CharField(blank=True, choices=[('Future-lab', 'Future-lab'), ('Webinar', 'Webinar'), ('Course-1', 'Conoscenza di sé e apertura a nuove prospettive'), ('Course-2', 'Conoscenza del mondo universitario/ITS'), ('Course-FS', 'Conoscenza di sé e del mondo universitario/its')], default='Webinar', max_length=50),
        ),
    ]
