# Generated by Django 3.2 on 2023-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0075_alter_studentpctorecord_pcto_hour_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactionitemfiles',
            name='file_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
