# Generated by Django 3.2 on 2023-05-29 06:23

from django.db import migrations
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0077_merge_20230525_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactionitemframework',
            name='answer',
            field=student.models.NoSortJSONField(blank=True),
        ),
    ]
