# Generated by Django 3.2 on 2023-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0078_alter_studentactionitemframework_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactionitemdiarycomment',
            name='comments_total_count',
            field=models.IntegerField(default=0),
        ),
    ]
