# Generated by Django 3.2 on 2023-07-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0080_auto_20230607_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcohortmapper',
            name='student_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_cohort_map', to='student.studentsplanmapper'),
        ),
        migrations.AddField(
            model_name='studentsplanmapper',
            name='is_current_active_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
