# Generated by Django 3.2 on 2023-07-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0080_auto_20230607_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActionItemDiaryAIComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=150)),
                ('AI_comment', models.TextField()),
                ('AI_comment_status', models.CharField(choices=[('Generated', 'Generated'), ('Published', 'Published'), ('Modified', 'Modified'), ('Modified Published', 'Modified Published')], default='generated', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_ai_comments', to=settings.AUTH_USER_MODEL)),
                ('student_action_item_diary_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments', to='student.studentactionitemdiarycomment')),
                ('student_actions_item_diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments_student_actions_item_diary', to='student.studentactionitemdiary')),
            ],
            options={
                'verbose_name': 'StudentActionItemDiaryAIComment',
                'verbose_name_plural': 'StudentActionItemDiaryAIComments',
                'ordering': ('created_at',),
            },
        ),
    ]
