# Generated by Django 3.2 on 2023-07-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0081_studentactionitemdiaryaicomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactionitemdiaryaicomment',
            name='AI_comment_status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Published', 'Published'), ('Cancelled', 'Cancelled'), ('Modified Published', 'Modified Published')], default='generated', max_length=20),
        ),
    ]
