# Generated by Django 3.2 on 2023-07-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0082_alter_studentactionitemdiaryaicomment_ai_comment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentactionitemdiaryaicomment',
            old_name='AI_comment',
            new_name='ai_comment',
        ),
        migrations.RenameField(
            model_name='studentactionitemdiaryaicomment',
            old_name='AI_comment_status',
            new_name='ai_comment_status',
        ),
        migrations.RemoveField(
            model_name='studentactionitemdiaryaicomment',
            name='student_action_item_diary_comment',
        ),
    ]
