# Generated by Django 3.2 on 2023-07-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0083_auto_20230707_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactionitemdiaryaicomment',
            name='student_action_item_diary_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_comments', to='student.studentactionitemdiarycomment'),
        ),
    ]
