# Generated by Django 3.2 on 2023-07-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0084_studentactionitemdiaryaicomment_student_action_item_diary_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactionitemdiaryaicomment',
            name='student_action_item_diary_comment',
        ),
    ]
