# Generated by Django 3.2 on 2023-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0085_remove_studentactionitemdiaryaicomment_student_action_item_diary_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactionitemdiaryaicomment',
            name='ai_comment_status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Published', 'Published'), ('Cancelled', 'Cancelled'), ('Modified Published', 'Modified Published')], default='Generated', max_length=20),
        ),
    ]
