# Generated by Django 3.2 on 2023-07-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0086_alter_studentactionitemdiaryaicomment_ai_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactionitemdiaryaicomment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentactionitemdiaryaicomment',
            name='person',
        ),
    ]
