# Generated by Django 3.2 on 2023-07-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0081_auto_20230706_0518'),
        ('student', '0087_auto_20230708_1350'),
    ]

    operations = [
    ]
