# Generated by Django 3.2 on 2023-11-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0091_auto_20231111_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='status',
            new_name='is_active',
        ),
    ]
