# Generated by Django 3.2 on 2023-11-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0092_rename_status_jobposting_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='end_date',
            new_name='job_date',
        ),
    ]
