# Generated by Django 3.2 on 2023-11-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0093_rename_end_date_jobposting_job_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
