# Generated by Django 3.2 on 2023-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0094_delete_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactionitemdiarycomment',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
