# Generated by Django 3.2 on 2021-07-30 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('event_name', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'CustomEvent',
                'verbose_name_plural': 'CustomEvent',
            },
        ),
    ]
