# Generated by Django 3.2 on 2021-08-02 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevent',
            name='event_type',
        ),
        migrations.AddField(
            model_name='customevent',
            name='browser',
            field=models.CharField(blank=True, choices=[(1, 'Chrome'), (2, 'FireFox'), (3, 'Edge'), (4, 'Safari'), (5, 'Opera'), (6, 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='browser_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='os',
            field=models.CharField(blank=True, choices=[(1, 'Windows'), (2, 'Linux'), (3, 'Android'), (4, 'iOS'), (5, 'macOS'), (6, 'iPadOS'), (7, 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='os_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='page_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customevent',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customevent',
            name='event_name',
            field=models.CharField(choices=[(1, 'Sign up - Stage 1'), (2, 'Sign up - Stage 2'), (3, 'Login'), (4, 'Payment - Success'), (5, 'Payment - Fail')], max_length=50),
        ),
    ]
