# Generated by Django 3.2 on 2021-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics', '0002_auto_20210802_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevent',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='customevent',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='customevent',
            name='os',
        ),
        migrations.RemoveField(
            model_name='customevent',
            name='os_version',
        ),
        migrations.AddField(
            model_name='customevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
