# Generated by Django 3.2 on 2021-08-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics', '0004_auto_20210802_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='custom_user_session_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customevent',
            name='event_id',
            field=models.CharField(choices=[(1, 'Sign up - Stage 1'), (2, 'Sign up - Stage 2'), (3, 'Login - Success'), (4, 'Login - Fail'), (5, 'Home'), (6, 'Students'), (7, 'High Schools'), (8, 'About us'), (9, 'dashboard')], max_length=50),
        ),
    ]
