# Generated by Django 3.2 on 2021-08-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_analytics', '0006_alter_customevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
