from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.admin_dashboard_view, name="admin_dashboard"),
    path("search/", views.futurely_admin_search_view,
         name="search_student_information"),
    path('student-performance/', views.counselor_stu_performance,
         name="student-performance"),
    path("bulk_email_panel/", views.bulk_email_panel_view,
         name="bulk_email_panel_view"),
    path("save_excel_file/", views.save_excel_file, name="save_excel_file"),
    path("scholarship-students-information/", views.scholarship_information_view,
         name="scholarship_students_information"),
    path("student-scholarship-details/", views.student_scholarship_detail,
         name="student_scholarship_details"),
    path("getcohort/", views.cohortfilter, name="cohortfilter"),
    path("coupon-code-filter/", views.discountcodefilter, name="discount_filter"),
    path("cohort-details/", views.CohortDetailsView.as_view(), name="cohort_details"),
    path("students-step-detail/<cohort_id>/<step_status_id>/",
         views.students_step_detail, name="students_step_detail"),
    path("send-push-notification/", views.SendPushNotificationView.as_view(),
         name='send_push_notification'),
    path("send-push-notification-by-cohort/", views.PushNotificationByCohort.as_view(),
         name='send_push_notification_by_cohort'),
    path("email_tracking_dashboard/", views.get_dynamodb,
         name="email_tracking_dashboard"),
    path("students-kpis/", views.student_performace_for_admin_view,
         name="admin_students_kpis"),
    path("scholarship-approved/", views.scholarship_approved_view,
         name="scholarship_approved"),
    path("scholarship-declied/", views.declied_scholarship_view,
         name="scholarship_declied"),
    path("submit-comment/", views.submit_comment_view, name="submit_comment"),
    path("excelfiledownload/", views.excelfiledownload, name="excelfiledownload"),
    path('account-settings-futurely-admin/', views.account_settings_view_futurely_admin,
         name="account-settings-futurely-admin"),
    path('ai-generated-comments/', views.ai_generated_comments_dashborad,
         name="ai_generated_data"),
    path('publish-and-modify-ai-commnets/',
         views.publish_and_modify_ai_commnets, name="publish_modify_ai_records"),
    path('remove-ai-generated-comment/',
         views.remove_ai_comments, name="remove_ai_record"),
    path('ai-generated-comments/<str:program_name>',
         views.filter_ai_generated_comments, name="filter_ai_generated_comments"),
]
