# Generated by Django 3.2 on 2021-06-29 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_intent_id', models.CharField(max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('status', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_region',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_type',
        ),
        migrations.AddField(
            model_name='person',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='are_you_a_student',
            field=models.CharField(choices=[('Are you a student?', 'Are you a student?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='are_you_sixteen_plus',
            field=models.CharField(choices=[('Are you 16+?', 'Are you 16+?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='StudentSchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('school_class', models.CharField(max_length=30, verbose_name='Class')),
                ('school_region', models.CharField(max_length=30)),
                ('school_city', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=30)),
                ('school_type', models.CharField(max_length=30)),
                ('school_year', models.CharField(max_length=30)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_school_detail', to='userauth.student')),
            ],
            options={
                'verbose_name': 'StudentSchoolDetail',
                'verbose_name_plural': 'StudentSchoolDetails',
            },
        ),
    ]
