# Generated by Django 3.2 on 2021-06-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20210629_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email_verified',
        ),
    ]
