# Generated by Django 3.2 on 2021-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_remove_person_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
