# Generated by Django 3.2 on 2021-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='are_you_sixteen_plus',
        ),
        migrations.AddField(
            model_name='student',
            name='are_you_fourteen_plus',
            field=models.CharField(choices=[('Are you 14+?', 'Are you 14+?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='are_you_from_futurelabs',
            field=models.CharField(choices=[('Are you from future labs?', 'Are you from future labs?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=30),
        ),
    ]
