# Generated by Django 3.2 on 2021-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20210810_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='futurelabs_coupon_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
