# Generated by Django 3.2 on 2021-08-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_student_futurelabs_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='are_you_from_futurelabs',
            field=models.CharField(choices=[('Are you enrolling from a future lab session?', 'Are you enrolling from a future lab session?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=70),
        ),
    ]
