# Generated by Django 3.2 on 2021-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_student_are_you_from_futurelabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='are_you_part_of_company_welfare_program',
            field=models.CharField(choices=[('Are you part of a company welfare program?', 'Are you part of a company welfare program?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
