# Generated by Django 3.2 on 2021-08-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_auto_20210823_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Italy', 'Italy')], default='Italy', max_length=70),
        ),
    ]
