# Generated by Django 3.2 on 2021-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='are_you_from_futurelabs',
            field=models.CharField(blank=True, choices=[('Are you enrolling from a future lab session?', 'Are you enrolling from a future lab session?'), ('Yes', 'Yes'), ('No', 'No')], default='Are you enrolling from a future lab session?', max_length=70),
        ),
        migrations.AlterField(
            model_name='student',
            name='are_you_part_of_company_welfare_program',
            field=models.CharField(blank=True, choices=[('Are you part of a company welfare program?', 'Are you part of a company welfare program?'), ('Yes', 'Yes'), ('No', 'No')], default='Are you part of a company welfare program?', max_length=70),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='class_name',
            field=models.CharField(choices=[('Select Class Name', 'Select Class Name'), ('A Class', 'A Class'), ('B Class', 'B Class'), ('D Class', 'D Class'), ('Select Class Name', 'Select Class Name'), ('A Class', 'A Class'), ('B Class', 'B Class'), ('C Class', 'C Class')], default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='class_year',
            field=models.CharField(choices=[('Select Class Year', 'Select Class Year'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year'), ('Select Class Year', 'Select Class Year'), ('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('5th Year', '5th Year')], default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='specialization',
            field=models.CharField(choices=[('Class Specialization', 'Class Specialization'), ('X', 'X'), ('Y', 'Y'), ('Class Specialization', 'Class Specialization'), ('Liceo - artistico', 'Liceo - artistico'), ('Liceo - classico', 'Liceo - classico'), ('Liceo - linguistico', 'Liceo - linguistico'), ('Liceo - musicale', 'Liceo - musicale'), ('Liceo - scientifico', 'Liceo - scientifico'), ('Liceo - scientifico scienze applicate', 'Liceo - scientifico scienze applicate'), ('Liceo - scientifico sportivo', 'Liceo - scientifico sportivo'), ('Liceo - scientifico tecnologico', 'Liceo - scientifico tecnologico'), ('Liceo - economico sociale', 'Liceo - economico sociale'), ('Liceo - scienze umane', 'Liceo - scienze umane'), ('Istituto tecnico', 'Istituto professionale'), ('Altro', 'Altro')], default='', max_length=70),
        ),
    ]
