# Generated by Django 3.2 on 2021-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0015_auto_20210824_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
