# Generated by Django 3.2 on 2021-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_alter_school_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='are_you_from_futurelabs',
            field=models.CharField(blank=True, choices=[('Are you enrolling from a future lab session?', 'Are you enrolling from a future lab session?'), ('Yes', 'Yes'), ('No', 'No')], default='Are you enrolling from a future lab session?', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='are_you_part_of_company_welfare_program',
            field=models.CharField(blank=True, choices=[('Are you part of a company welfare program?', 'Are you part of a company welfare program?'), ('Yes', 'Yes'), ('No', 'No')], default='Are you part of a company welfare program?', max_length=70, null=True),
        ),
    ]
