# Generated by Django 3.2 on 2021-08-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0018_auto_20210825_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='are_you_fourteen_plus',
            field=models.CharField(choices=[(None, 'Are you 14+?'), ('Yes', 'Yes'), ('No', 'No')], default='', max_length=30),
        ),
    ]
