# Generated by Django 3.2 on 2021-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0019_alter_student_are_you_fourteen_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='are_you_from_futurelabs',
            field=models.CharField(blank=True, choices=[(None, 'Are you enrolling from a future lab session?'), ('Yes', 'Yes'), ('No', 'No')], max_length=70, null=True),
        ),
    ]
