# Generated by Django 3.2 on 2021-08-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0024_auto_20210825_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company_name',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Italy', 'Italy')], default='Italy', max_length=70),
        ),
    ]
