# Generated by Django 3.2 on 2021-08-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0025_auto_20210825_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='userauth.company'),
            preserve_default=False,
        ),
    ]
