# Generated by Django 3.2 on 2021-08-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0026_student_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='company_name',
            new_name='company',
        ),
    ]
