# Generated by Django 3.2 on 2021-08-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0028_classname_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='ClassYear',
        ),
        migrations.AlterModelOptions(
            name='classyear',
            options={'verbose_name': 'ClassYear', 'verbose_name_plural': 'ClassYears'},
        ),
    ]
