# Generated by Django 3.2 on 2021-08-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0031_auto_20210825_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschooldetail',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.classname'),
        ),
        migrations.AddField(
            model_name='studentschooldetail',
            name='class_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.classyear'),
        ),
        migrations.AddField(
            model_name='studentschooldetail',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.specialization'),
        ),
    ]
