# Generated by Django 3.2 on 2021-08-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0033_auto_20210825_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschooldetail',
            name='class_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.classyear'),
        ),
    ]
