# Generated by Django 3.2 on 2021-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0034_alter_studentschooldetail_class_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschooldetail',
            name='school_class',
        ),
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='userauth.company'),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.classname'),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='class_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.classyear'),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_region',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_year',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_school_details', to='userauth.specialization'),
        ),
    ]
