# Generated by Django 3.2 on 2021-08-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0035_auto_20210825_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentschooldetail',
            old_name='school_year',
            new_name='graduation_year',
        ),
    ]
