# Generated by Django 3.2 on 2021-08-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0036_rename_school_year_studentschooldetail_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='are_you_from_futurelabs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='are_you_part_of_company_welfare_program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='futurelabs_coupon_code',
        ),
        migrations.AddField(
            model_name='student',
            name='discount_coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
