# Generated by Django 3.2 on 2021-08-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0038_student_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='src',
            field=models.CharField(blank=True, choices=[('future_lab', 'future_lab'), ('company', 'company'), ('general', 'general')], default='general', max_length=50),
        ),
    ]
