# Generated by Django 3.2 on 2021-09-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0039_alter_student_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='future_lab_form_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='future_lab_form_status',
            field=models.BooleanField(default=False),
        ),
    ]
