# Generated by Django 3.2 on 2021-10-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0042_auto_20210921_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='userauth.company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='discount_coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='src',
            field=models.CharField(blank=True, choices=[('future_lab', 'future_lab'), ('company', 'company'), ('general', 'general')], default='general', max_length=50, null=True, verbose_name='Source'),
        ),
    ]
