# Generated by Django 3.2 on 2021-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0044_alter_studentschooldetail_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_of_plans',
            field=models.CharField(blank=True, default='3', max_length=10, null=True),
        ),
    ]
