# Generated by Django 3.2 on 2021-10-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0045_student_number_of_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('school_region', models.CharField(blank=True, default='', max_length=30)),
                ('school_city', models.CharField(blank=True, default='', max_length=30)),
                ('school_name', models.CharField(blank=True, default='', max_length=30)),
                ('is_verified_by_futurely', models.BooleanField(default=False)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counselor',
                'verbose_name_plural': 'Counselors',
            },
        ),
    ]
