# Generated by Django 3.2 on 2021-10-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0046_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='school_city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='school_region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentschooldetail',
            name='school_region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
