# Generated by Django 3.2 on 2021-11-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0047_auto_20211027_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='number_of_plans',
            new_name='number_of_offered_plans',
        ),
    ]
