# Generated by Django 3.2 on 2021-11-16 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0050_alter_student_are_you_a_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('region', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('Italy', 'Italy')], default='Italy', max_length=70)),
            ],
            options={
                'verbose_name': 'CountryDetail',
                'verbose_name_plural': 'CountryDetails',
            },
        ),
    ]
