# Generated by Django 3.2 on 2021-11-19 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0051_countrydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
