# Generated by Django 3.2 on 2022-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0054_auto_20220214_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender_other',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
