# Generated by Django 3.2 on 2022-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0055_alter_person_gender_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skip_course_dependency',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
