# Generated by Django 3.2 on 2022-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0056_student_skip_course_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_course1_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
