# Generated by Django 3.2 on 2022-02-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0058_student_is_display_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_display_discount_price',
            new_name='display_discounted_price',
        ),
    ]
