# Generated by Django 3.2 on 2022-02-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0059_rename_is_display_discount_price_student_display_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='display_discounted_price',
            new_name='display_discounted_price_only',
        ),
    ]
