# Generated by Django 3.2 on 2022-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0060_rename_display_discounted_price_student_display_discounted_price_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lang_code',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], max_length=20, null=True),
        ),
    ]
