# Generated by Django 3.2 on 2022-07-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0061_auto_20220506_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='counselors', to='userauth.company'),
        ),
    ]
