# Generated by Django 3.2 on 2022-07-20 05:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0062_counselor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParentsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_email', models.CharField(default='', max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_detail', to='userauth.student')),
            ],
            options={
                'verbose_name': 'StudentParentsDetail',
                'verbose_name_plural': 'StudentParentsDetails',
            },
        ),
    ]
