# Generated by Django 3.2 on 2022-08-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0062_counselor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_message', models.CharField(blank=True, max_length=250, null=True)),
                ('lang_code', models.CharField(blank=True, choices=[('en-us', 'English'), ('it', 'Italiano')], max_length=20, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delete_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
