# Generated by Django 3.2 on 2022-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0063_studentparentsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_pcto_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
