# Generated by Django 3.2 on 2022-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0063_studentdeleterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdeleterequest',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='studentdeleterequest',
            name='is_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Processed', 'Processed')], default='Requested', max_length=20),
        ),
    ]
