# Generated by Django 3.2 on 2022-07-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0064_masterotp'),
        ('userauth', '0064_student_total_pcto_hours'),
    ]

    operations = [
    ]
