# Generated by Django 3.2 on 2022-08-16 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0065_auto_20220816_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdeleterequest',
            name='reason_message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='studentdeleterequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delete_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
