# Generated by Django 3.2 on 2022-08-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0066_alter_masterotp_options'),
        ('userauth', '0066_auto_20220816_1714'),
    ]

    operations = [
    ]
