# Generated by Django 3.2 on 2022-11-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0068_counselor_academic_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='academic_section',
            new_name='academic_session_start_date',
        ),
    ]
