# Generated by Django 3.2 on 2022-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0070_alter_counselor_academic_session_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_from_middle_school',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
