# Generated by Django 3.2 on 2022-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0071_student_is_welcome_video_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_step1_pdf_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
