# Generated by Django 3.2 on 2022-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0072_student_is_step1_pdf_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparentsdetail',
            name='parent_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
