# Generated by Django 3.2 on 2022-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0073_studentparentsdetail_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
