# Generated by Django 3.2 on 2022-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0071_student_is_from_middle_school'),
        ('userauth', '0074_counselor_coupon_code'),
    ]

    operations = [
    ]
