# Generated by Django 3.2 on 2023-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0075_merge_20221216_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparentsdetail',
            name='parent_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
