# Generated by Django 3.2 on 2023-02-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0079_student_is_from_fast_track_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_channel',
            field=models.CharField(blank=True, default='free_channel', max_length=50, null=True),
        ),
    ]
