# Generated by Django 3.2 on 2023-04-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0080_student_student_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentparentsdetail',
            name='parent_email_from_reg',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
