# Generated by Django 3.2 on 2023-06-19 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0081_studentparentsdetail_parent_email_from_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorWithSpecialDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('counselor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_with_special_dashboard', to='userauth.counselor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
