# Generated by Django 3.2 on 2023-06-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0083_auto_20230628_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['name'], 'verbose_name': 'ClassName', 'verbose_name_plural': 'ClassNames'},
        ),
    ]
