# Generated by Django 3.2 on 2023-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0084_alter_classname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='clarity_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
