# Generated by Django 3.2 on 2023-07-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0085_person_clarity_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='is_trial_account',
            field=models.BooleanField(default=False),
        ),
    ]
