# Generated by Django 3.2 on 2023-07-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0086_auto_20230713_1112'),
        ('userauth', '0086_counselor_is_trial_account'),
    ]

    operations = [
    ]
