# Generated by Django 3.2 on 2023-07-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0087_merge_20230714_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselor',
            name='is_trial_account',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
