# Generated by Django 3.2 on 2023-09-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0089_auto_20230823_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubspotCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'HubspotCredential',
                'verbose_name_plural': 'HubspotCredentials',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_blocked',
        ),
    ]
