# Generated by Django 3.2 on 2023-09-27 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0092_auto_20230913_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWithSchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.company')),
                ('school', models.ManyToManyField(to='userauth.School')),
            ],
            options={
                'verbose_name': 'CompanyWithSchoolDetail',
                'verbose_name_plural': 'CompanyWithSchoolDetails',
            },
        ),
    ]
