# Generated by Django 3.2 on 2023-09-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0093_companywithschooldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywithschooldetail',
            name='is_for_high_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companywithschooldetail',
            name='is_for_middle_school',
            field=models.BooleanField(default=False),
        ),
    ]
