# Generated by Django 3.2 on 2023-09-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0096_auto_20230927_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='company_path_type',
        ),
    ]
