# Generated by Django 3.2 on 2023-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0114_myblogvideos_duration'),
        ('userauth', '0097_remove_school_company_path_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='plans',
            field=models.ManyToManyField(blank=True, null=True, to='courses.OurPlans'),
        ),
    ]
