# Generated by Django 3.2 on 2023-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0098_counselor_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
