# Generated by Django 3.2 on 2023-11-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0100_companydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='userauth.company'),
        ),
    ]
