# Generated by Django 3.2 on 2023-12-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0101_alter_companydetail_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_sponsor_compnay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stu_sponsor_company', to='userauth.company'),
        ),
    ]
